### ISSUE TITLE
可以增加搜狗翻译API吗？

### ISSUE THREAD

**Issue by drockser** [PantsuDango/Dango-Translator#10]
https://deepi.sogou.com/doccenter/texttranslatedoc
如上所述

**Comment by PantsuDango** [comment]
它没有免费额度吗？如果没有，我会考虑爬虫来爬他们的网页翻译接口了...不然没有免费额度加进去没有意义

**Comment by drockser** [comment]
免费额度是新用户赠送100元体验劵，但是没有每月免费多少字节这样子的。

**Comment by PantsuDango** [comment]
如果没有每月固定免费额度的话，那就不能考虑啦，不过我可以考虑加入它的网页接口，用爬虫
