### ISSUE TITLE
能不能每次都自动朗读原文啊？有Azure API

### ISSUE THREAD

**Issue by mikudate** [PantsuDango/Dango-Translator#100]
如题，玩韩语游戏不发音就听不懂。每次点又手累

**Comment by PantsuDango** [comment]
可以有，下次更新就安排




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年12月1日(星期四) 下午4:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 能不能每次都自动朗读原文啊？有Azure API (Issue #100)





 
如题，玩韩语游戏不发音就听不懂。每次点又手累

**Comment by PantsuDango** [comment]
自动朗读已经在最新版本添加了，此issu我先关闭啦~
