### ISSUE TITLE
readme.md中交流群号显示错误

### ISSUE THREAD

**Issue by xjn6666** [PantsuDango/Dango-Translator#101]
readme中显示 交流群16是32523865，但实际上应该是432523865（B站找到的）

**Comment by PantsuDango** [comment]
感谢提醒！！！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月2日(周五) 凌晨0:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] readme.md中交流群号显示错误 (Issue #101)




 
readme中显示 交流群16是32523865，但实际上应该是432523865（B站找到的）

**Comment by PantsuDango** [comment]
群号已修复，此issu我就先关闭啦~谢谢！
