### ISSUE TITLE
[请求]能否提供一份编译项目的spec文件

### ISSUE THREAD

**Issue by luis-arch** [PantsuDango/Dango-Translator#103]
作者，本人想基于您的源代码，调用本人的翻译api进行翻译。所以我下载了最新的源代码并且写好了代码，但是在最后pyinstaller编译成exe出错了，请问您可否告知您编译此项目的方法？假如您是使用pyinstaller，能提供一份spec文件就再好不过了。

我知道本人的要求也许确实对您生活造成了麻烦，在这我先提前跟您说句对不起。假如不方便的话，您可以自由选择关闭issue，或者直接不管这份请求，本人也会在一周后无回复关闭issue。

希望得到您的体谅与帮助。

**Comment by PantsuDango** [comment]
我使用的是pyinstaller，编译命令是
`G:\Python\Python38\Scripts\pyinstaller.exe app.py -w --uac-admin -i H:\work\dango\团子打包用\config\icon\logo.ico`
`G:\Python\Python38\Scripts\pyinstaller.exe` 为pyinstaller的执行文件路径
`app.py` 为翻译器的主程序文件路径
`-w` 为打包后不带cmd调试窗口
`--uac-admin` 为默认管理员启动
`-i H:\work\dango\团子打包用\config\icon\logo.ico` 为exe添加图标

目前最新版本4.4.0打包时的spec文件 [app.spec](https://l2.drive.c4a15wh.cn/api/v3/slave/source/0/dXBsb2Fkcy8yLzIwMjMvMDEvMDQvQVh4REs5Ym5fYXBwLnNwZWM/app.spec?sign=YClyARCKXel33GAl44SwpXwQEQ9cPD5bWzbXkZTpIaw%3D%3A0)

**Comment by luis-arch** [comment]
感谢作者
