### ISSUE TITLE
無法運行本地OCR

### ISSUE THREAD

**Issue by hszrnim** [PantsuDango/Dango-Translator#104]
<img width="721" alt="image" src="https://user-images.githubusercontent.com/113572740/211997006-2c9f9ae4-0be8-46d0-9b1d-6ec57dbf1a9e.png">

**Comment by PantsuDango** [comment]
请参考如下教程解决：https://docs.dango.c4a15wh.cn/#/4.0/FAQ/faq?id=gbk%e8%a7%a3%e7%a0%81%e9%94%99%e8%af%af

**Comment by C4a15Wh** [comment]
您好，上述地址已失效，请查阅: https://docs2.ayano.top/#/4.0/FAQ/faq?id=gbk%E8%A7%A3%E7%A0%81%E9%94%99%E8%AF%AF

**Comment by hszrnim** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/113572740/212214774-ad0c251e-a951-4b20-a5d1-8f5f4aa19eeb.png">
<img width="752" alt="image" src="https://user-images.githubusercontent.com/113572740/212214923-97584af8-7246-461f-865a-0b50c83e3bab.png">
跟了上面那個網址run, 還是有報錯

**Comment by PantsuDango** [comment]
可能是你的繁体系统编码和简体冲突问题...
这里有一个新打包的 ocr，可以下载来试试 https://drive.ayano.top/s/5GtE
用我提供的 ocr 包，按照如下提示替换翻译器里的 ocr
https://docs2.ayano.top/#/4.0/FAQ/faq?id=%e6%9b%bf%e6%8d%a2%e6%9c%ac%e5%9c%b0ocr

如果以上方法仍未解决：
+ 将繁体系统改为简体
+ 考虑使用在线 ocr

**Comment by hiroi-sora** [comment]
哈哈，小黑厨+1

顺便我[项目](https://github.com/hiroi-sora/Umi-OCR)也是基于PaddleOCR（不过是c++），也遇到了系统区域与语言编码的坑。最后引擎内调用的系统API全部换成宽字节wstring型，输入输出则用string u8。就摆脱了对gbk编码的依赖，能在其它区域/系统编码的windows上跑。

**Comment by PantsuDango** [comment]
最新版本的本地OCR应该不会再出现此问题，可以尝试更新，详见 [B站动态](https://www.bilibili.com/opus/765552391458127952?spm_id_from=333.999.0.0)
