### ISSUE TITLE
私人翻译能否调用有道翻译

### ISSUE THREAD

**Issue by null-qwerty** [PantsuDango/Dango-Translator#105]
能否使用有道翻译api？

**Comment by PantsuDango** [comment]
团子是这样考虑的，我希望私人翻译是免费且可持续用的，但是有道的私人这边虽然说有免费额度，但是是一次性的，用完也不会像其他每个月会重置，所以没有接入有道的私人

**Comment by PantsuDango** [comment]
未有进一步反馈，暂时关闭
