### ISSUE TITLE
[Enhancement] 支持 ChatGPT 翻译

### ISSUE THREAD

**Issue by szh-bash** [PantsuDango/Dango-Translator#106]
偶然路过此项目，不知作者是否有意添加此功能，还是已经添加！
- 调用自定义 OpenAI API
- 调用网页版 ChatGPT 作为备用方案

**Comment by PantsuDango** [comment]
在开发计划里了～但是太忙了还没时间做，肯定要接入的！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月10日(周五) 下午2:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] [Enhancement] 支持 ChatGPT 翻译 (Issue #106)




 
偶然路过此项目，不知作者是否有意添加此功能，还是已经添加！
  
调用自定义 OpenAI API
 
调用网页版 ChatGPT 作为备用方案

**Comment by szh-bash** [comment]
期待！

**Comment by PantsuDango** [comment]
自定义 OpenAI AP I的功能已更新并发布于 [Ver4.5.4](https://github.com/PantsuDango/Dango-Translator/releases/tag/Ver4.5.4) 版本，请更新后体验
详见 [B站动态](https://www.bilibili.com/opus/814141966142930996?spm_id_from=333.999.0.0)
