### ISSUE TITLE
已解决，编辑

### ISSUE THREAD

**Issue by edward21347** [PantsuDango/Dango-Translator#107]
已解决编辑

**Comment by PantsuDango** [comment]
在框的右下角可以调节







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月22日(星期三) 中午12:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 翻译文本显示区域能否调整 (Issue #107)





 
没找到在哪里调整，使用笔记本屏幕不够大，默认区域常常和范围重合

**Comment by PantsuDango** [comment]
问题解决，关闭
