### ISSUE TITLE
是否可以提供对登录界面及翻译框的分辨率调节？

### ISSUE THREAD

**Issue by birrush** [PantsuDango/Dango-Translator#109]
在某次使用时，注意到登陆界面明显大于预期。希望可以在设置中添加调节功能，以便手动控制大小

**Comment by PantsuDango** [comment]
您好，我在初始化gui窗口时，是有设置分辨率自适应的。我想知道你具体遇到了什么情况？你可以附带你的截图给我看看吗？感谢。



---原始邮件---
发件人: "Birrush ***@***.***&gt;
发送时间: 2023年4月25日(周二) 凌晨2:53
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 是否可以提供对登录界面及翻译框的分辨率调节？ (Issue #109)




 
在某次使用时，注意到登陆界面明显大于预期。希望可以在设置中添加调节功能，以便手动控制大小
