### ISSUE TITLE
可不可以加一个批量翻译字幕srt的功能？

### ISSUE THREAD

**Issue by zx3777** [PantsuDango/Dango-Translator#110]
麻烦了，谢谢！

**Comment by PantsuDango** [comment]
团子觉得比起在翻译器加上这种功能，是否考虑直接使用现成会更方便：https://github.com/speauty/anto

**Comment by zx3777** [comment]
> 团子觉得比起在翻译器加上这种功能，是否考虑直接使用现成会更方便：https://github.com/speauty/anto

谢谢推荐
