### ISSUE TITLE
发送验证码邮件失败

### ISSUE THREAD

**Issue by ChenghanMan** [PantsuDango/Dango-Translator#112]
点击获取验证码按钮后，弹出弹窗：

**发送验证码邮件失败了！
SendEmailError
请直接联系团子解决**

**Comment by PantsuDango** [comment]
此问题已修复，请重试




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月1日(星期一) 中午12:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 发送验证码邮件失败 (Issue #112)





 
点击获取验证码按钮后，弹出弹窗：
 
发送验证码邮件失败了！
 SendEmailError
 请直接联系团子解决

**Comment by ChenghanMan** [comment]
问题已解决，谢谢！
