### ISSUE TITLE
能否提供一个本地TTS接口 

### ISSUE THREAD

**Issue by nagisa-eevee** [PantsuDango/Dango-Translator#113]
我目前的方案是，监控团子输出到剪贴板的OCR内容，采用vits([代码](https://github.com/Plachtaa/VITS-fast-fine-tuning)|[预训练模型](https://www.bilibili.com/video/BV1rR4y197KD))作为TTS模型自动朗读。但是这个方案会朗读所有剪贴板内容。有没有可能实现一个外挂接口，让我在不需要二次开发的情况下，只朗读团子OCR识别的结果？

**Comment by PantsuDango** [comment]
可以换个思路，尝试从"翻译历史.txt"（这个文件在翻译器安装的根目录）里面读取，所有识别和翻译的结果都会输出到这里，可以从这里读取原文结果来朗读




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月2日(星期二) 上午10:16
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 能否提供一个本地TTS接口  (Issue #113)





 
我目前的方案是，监控团子输出到剪贴板的OCR内容，采用vits(代码|预训练模型)作为TTS模型自动朗读。但是这个方案会朗读所有剪贴板内容。有没有可能实现一个外挂接口，让我在不需要二次开发的情况下，只朗读团子OCR识别的结果？

**Comment by nagisa-eevee** [comment]
好的，谢谢！

**Comment by PantsuDango** [comment]
已实现，新版本自带本地TTS模型朗读（5.x以上）
