### ISSUE TITLE
功能请求……

### ISSUE THREAD

**Issue by DevilPaean** [PantsuDango/Dango-Translator#115]
1、现在只支持对翻译回来的结果进行自动修改，可否将ocr识别到的文字进行自动修改呢，这样可以将人名地名之类的翻译保持一致
2、文字相似度的修改目前只支持下限80%，可否去掉限制，因为玩一些有战斗的游戏的时候经常会将战斗栏进行反复翻译……
3、本地ocr识别文字变动后再将图片传给在线ocr精确识别，现在的本地识别字体差的英文有点吃力……
4、能否加一个开启关闭自动翻译的快捷键，我看去年有人提了……目前我是用的按键精灵点开关……
谢谢大大么么哒~
![16UA%QT)N(EMX77 @I`BXLH](https://github.com/PantsuDango/Dango-Translator/assets/18099909/f05fcda1-0530-43a7-9971-2c1879a5bb6e)

**Comment by PantsuDango** [comment]
1. 目前的屏蔽词与替换词功能，是同时支持对ocr的结果和翻译的结果进行修改的；
2. 对战斗栏进行反复翻译，得分具体情况来看，一般我都是不会把非对话性的文本区域框在范围内的。关于80的阈值，我这边测试低于80以后效果挺不好的，所以设置了这个限制。你可以把你的case发我看看吗，你怎么框的；
3. 先给本地ocr识别一遍，再给在线ocr识别一遍，没有理解这样做的好处和用意。如果有能使用在线ocr，直接用在线ocr不就可以了么；
4. 采纳

**Comment by DevilPaean** [comment]
1、啊对不起……之前看教程页面红色的原文和译文有点小我下意识给跳过去了……实在抱歉……
2、有的游戏对话框和战斗状态都会显示在屏幕下方，既然效果不好那就忽略掉吧，我大片对话的时候手动开自动翻译就好
3、对不起我好像误会了，我原来以为设置刷新频率1秒的话一小时会消耗3600次，刚才试了下好像只有文字变化才会加次数？我这刚搬完家还没网一直没用在线ocr……
谢谢大大回复……
