### ISSUE TITLE
openAI是否可以增加自定义模型

### ISSUE THREAD

**Issue by Phosphenenene** [PantsuDango/Dango-Translator#116]
用gpt-3.5-turbo-16k-0613翻译速度会快

谢谢大大~

**Comment by PantsuDango** [comment]
收到，我自己也试了，是会快一点，等我周末发个新版本会替换gpt的模型，谢谢提醒！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月15日(星期四) 下午3:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] openAI是否可以增加自定义模型 (Issue #116)





 
用gpt-3.5-turbo-16k-0613翻译速度会快
 
谢谢大大~

**Comment by PantsuDango** [comment]
最新版本的chatgpt已更新为0613模型~ 欢迎更新使用

**Comment by PantsuDango** [comment]
自定义ChatGPT模型的功能已更新并发布于 [Ver4.5.4](https://github.com/PantsuDango/Dango-Translator/releases/tag/Ver4.5.4) 版本，请更新后体验
详见 [B站动态](https://www.bilibili.com/opus/814141966142930996?spm_id_from=333.999.0.0)
