### ISSUE TITLE
优化请求。。

### ISSUE THREAD

**Issue by cn-hideyoshi** [PantsuDango/Dango-Translator#117]
翻译框锁定后，除解锁按钮外的其他地方鼠标点击无法穿透，会使部分游戏的体验变差。
能否优化成歌词那种锁定后鼠标点击可以穿透的效果?

**Comment by PantsuDango** [comment]
我觉得合理且有意义，我会计划在未来实现并加入，非常感谢提供优化建议~

**Comment by PantsuDango** [comment]
鼠标穿透功能已在**Ver4.5.6**版本实现，当点击锁按钮后，翻译框将实现鼠标穿透

更新下载：
[github releases](https://github.com/PantsuDango/Dango-Translator/releases/tag/Ver4.5.6)
[官网](https://translator.dango.cloud/)
