### ISSUE TITLE
github release过时 官网下载速度极慢

### ISSUE THREAD

**Issue by anita739** [PantsuDango/Dango-Translator#118]
> 因安装包文件过大，软件下载请前往[团子翻译器官网](https://translator.dango.cloud/)进行下载，新版本不再发布github Releases

无法理解这其中的逻辑 以300多M的安装包过大为理由没有github release是否太牵强？
官网下载速度在不同网络下差异极大 本人下载速度只有57KB/s 引导到官方下载何必多此一举？
传个release 省的也是你们自己的流量

**Comment by PantsuDango** [comment]
很有道理，我已经将最新版本推送至github release了，地址如下：https://github.com/PantsuDango/Dango-Translator/releases/tag/Ver4.5.2
以后我会保持新版本同步至github release
非常感谢指出不足
