### ISSUE TITLE
[Enhancement] ChatGPT翻译希望可以配置api url

### ISSUE THREAD

**Issue by CJY-C** [PantsuDango/Dango-Translator#119]
Pandora项目已经提供了token转api的服务（虽说是模拟的api服务，但是请求和返回完全兼容，牛！），参见：https://github.com/pengzhile/pandora/issues/837

本地编译测试了下，速度挺快的：
![image](https://github.com/PantsuDango/Dango-Translator/assets/123308212/edcd862c-311f-42f3-bcf0-1e0beddeb5ac)

所以希望团子大大能把url配置整合到ui中：
![image](https://github.com/PantsuDango/Dango-Translator/assets/123308212/130f4e25-e0c4-4f4f-9137-894dfdcb9301)

**Comment by PantsuDango** [comment]
采纳，我会把chatgpt自定义请求地址做成可以编辑的



---原始邮件---
发件人: "Chen ***@***.***&gt;
发送时间: 2023年6月22日(周四) 下午2:29
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] [Enhancement] ChatGPT翻译希望可以配置api url (Issue #119)




 
Pandora项目已经提供了token转api的服务（虽说是模拟的api服务，但是请求和返回完全兼容，牛！），参见：pengzhile/pandora#837
 
本地编译测试了下，速度挺快的：
 
 
所以希望团子大大能把url配置整合到ui中：

**Comment by PantsuDango** [comment]
此功能已更新并发布于 [Ver4.5.4](https://github.com/PantsuDango/Dango-Translator/releases/tag/Ver4.5.4) 版本，请更新后体验
详见 [B站动态](https://www.bilibili.com/opus/814141966142930996?spm_id_from=333.999.0.0)
