### ISSUE TITLE
翻译快捷键失灵

### ISSUE THREAD

**Issue by neetnya** [PantsuDango/Dango-Translator#12]
点了启动翻译快捷键之后
一开始是可以正常使用的
几分钟之后就怎么按都没有反应
手动点按钮是可以用的

**Comment by PantsuDango** [comment]
已收到这个问题，推测是和其他应用的快捷键冲突，会尝试修复或加入双键作为快捷键

**Comment by planegoose** [comment]
我也遇到了这个问题
3.4刚打开的时候快捷键能使用,按了几次之后就不行了
但是3.3用起来就是正常的[疑惑]

**Comment by PantsuDango** [comment]
能具体告诉我，3.4版本你使用多久后，会出现快捷键失灵。然后3.3版本测试了多久都有效

**Comment by planegoose** [comment]
3.3一直没问题
3.4除了用一段时间就快捷键失灵之外,还会有卡死现象,我统计了一下两者出现的频次
【统计序号】   【快捷键失灵】   【卡死】
         1                         10                    71 
         2                         10                    70
         3                          9                     68
         4                         10                    73
         5                         10                    69    
(数值表示打开软件后翻译了多少次会出现问题)
可以看到,排除人工计数的误差影响,基本上每次都是跑10次会出现快捷键失灵,跑70次出现卡死现象,基本排除是偶然现象的可能。
尝试百度解决,试了用以win7、win8兼容模式运行、以管理员身份运行,都无果。以我浅薄的计算机知识,就真不知道是哪里出问题了。可能也只是单纯的我电脑有问题。
不过其实都是小bug,不太影响使用,所以目前就这么玩着也还好。

**Comment by nacl1415** [comment]
我的版本3.6.2 也是使用一段時間後就失效了~
重開後一開始可用~但一段時間後又失效

**Comment by PantsuDango** [comment]
此问题在最新版本已修复，如果仍然出现可能是快捷键冲突，可以试试重启软件
