### ISSUE TITLE
关于漫画方面的一点汉化辅助建议

### ISSUE THREAD

**Issue by chencxt** [PantsuDango/Dango-Translator#122]
先叠甲，鄙人从2019年疫情开始在家断断续续地汉化一些不正常的本子和正经漫画，接过私人单子，也干过正经的派发任务。作为一体机，能看到国内有如此多开发者帮忙优化汉化工作流，不胜感激。
1.关于chatgpt的api：chatgpt及其类似的AI项目算是近年来对汉化模式最大的冲击了，可以预见，由于汉化成本的降低，漫画汉化组的存在形式将在未来受到打击。但是有部分人（比如我）并没有使用官方的api接口的条件（visa、银联支付之类），而是使用的国内其他镜像商的接口，希望可以添加对其他Url的支持。
2.关于一键翻译：总结起来就是：**速度很快，但是自定义程度仍需改进**。我目前使用的是Imagetrans（在2019年，这个地位还是LabelPlus无可替代，没想到短短四年就能淘汰老辅助工具了），并没有使用团子作为主要辅助汉化工具，一个重要原因就是您的输出项目中，鄙人并没有找到对于PSD的输出支持，对于一个嵌字老油条而言，修图方面的限制非常大（许多具有精修图片能力的嵌字都无法发挥自己的实力）。另一个原因就是拟声词的识别，由于拟声词常常和框外字一起出现，对于这类变性字体的识别我也很清楚是个麻烦又不讨好的工作，所以在此希望可以添加一个“可以添加、编辑识别框及其内容”的功能，对于字体也是。Imagetrans在这方面在我看来就是与团子翻译器反其道而行之，每一步都需要手动微调反而显得麻烦了。
3.关于导入：由于汉化在时间尺度上的规模从几小时到几年都有，所以对于较大规模的汉化需求（如CG、漫画单行本）希望可以添加工程文件，让翻译或校对员可以反复推敲其逻辑性。我往往是自己翻译自己校对所以感觉不出来什么，但是对于汉化组或成建制的翻译组织而言，保证翻译正确比图像质量更重要。
4.关于收费模式：由于某些汉化行为并不是可以持续很久的，尤其是为爱发电，所以对于那种容易退却热情和接单不稳定的汉化个体户而言，他们并非每个月都有固定的汉化生产量，所以希望可以在按时间收费的基础上增加一个按使用次数收费的套餐。
总结，可能是您及您的开发组对于漫画汉化的流程的不了解，导致了功能的缺失。团子翻译器目前在鄙人看来，已经从一个圈地自萌的gal机翻软件，开始向着正经汉化的路子走。我不反对将机翻应用于传统汉化中（事实上，我和我的一些同事也经常在英语文献翻译需求上用机翻+人工校对糊弄顾客，某个角度讲，我很庆幸当初自己专业的第二语种选了日语而非俄语），但是机器翻译、乃至机器汉化，应该是提高生产力的手段，而非工作偷懒的理由。
如果您认为我的建议有失偏颇，请联系我删除此issues。再次向用技术改进生产的先行者表达敬意。

**Comment by PantsuDango** [comment]
太惊讶了，很感谢能对这个新功能做出这么多评价和建议，非常非常感谢~
我逐个回复你的问题点：
+ 支持自定义url这点，采纳，本周内会完成更新并发布
+ 支持导出psd格式，这点我会加入到开发计划里，以后会更新上
+ “可以添加、编辑识别框及其内容”这点，采纳，本周内会完成更新并发布
+ 关于添加工程文件，我不太理解这里提的工程文件都包含什么，目前团子这边翻译过的图片都会自动生成缓存目录，在你导入图片同级目录有个dango_manga文件夹，里面有ocr的结果、遮蔽图、消除文字后的图还有翻译记录和翻译完成的图这些文件缓存，你说的是不是这个呢。完成过翻译和编辑的图片，再次导入此目录，都会保留之前编辑翻译的状态。
+ 关于收费模式支持按次数的问题，这个我们是想支持的，但是因为我们的网关层在早期设计的时候，没有设计得很到位，没有支持按照次数这样的模式，要实现这点需要重构网关层的的代码逻辑，属于比较大的工程动作。我们是计划要做按次数收费的模式的，但是可能没法马上发布，需要点时间推敲重构这块逻辑，还请见谅。

**Comment by chencxt** [comment]
> 太惊讶了，很感谢能对这个新功能做出这么多评价和建议，非常非常感谢~ 我逐个回复你的问题点：
> 
> * 支持自定义url这点，采纳，本周内会完成更新并发布
> * 支持导出psd格式，这点我会加入到开发计划里，以后会更新上
> * “可以添加、编辑识别框及其内容”这点，采纳，本周内会完成更新并发布
> * 关于添加工程文件，我不太理解这里提的工程文件都包含什么，目前团子这边翻译过的图片都会自动生成缓存目录，在你导入图片同级目录有个dango_manga文件夹，里面有ocr的结果、遮蔽图、消除文字后的图还有翻译记录和翻译完成的图这些文件缓存，你说的是不是这个呢。完成过翻译和编辑的图片，再次导入此目录，都会保留之前编辑翻译的状态。
> * 关于收费模式支持按次数的问题，这个我们是想支持的，但是因为我们的网关层在早期设计的时候，没有设计得很到位，没有支持按照次数这样的模式，要实现这点需要重构网关层的的代码逻辑，属于比较大的工程动作。我们是计划要做按次数收费的模式的，但是可能没法马上发布，需要点时间推敲重构这块逻辑，还请见谅。

是的，鄙人希望可以把同级目录、缓存目录，及其里面的东西（总之就是和本次漫画汉化行为相关的所有东西），全部变成一个方便转移和存储的“工程文件”。这样可以让较大规模的翻译任务分发给其他人时，免去压缩再发送的麻烦（毕竟一个一个地转移小文件，即使在本地硬盘也很慢）。至于收费模式的问题只能深感抱歉了。不过如果你们想要快速创收回本的话，与其等待用户缴费，不如拉几个网络广告商，在应用里面开个空白板块多嵌入几个广告比较好？photopea的作者就是个不错的例子。

**Comment by PantsuDango** [comment]
工程文件，目前我想到就是一个压缩包的形式...不把整个工作目录压缩，然后就可以发给别人了，没想到有什么更好的形式
至于广告收费，抱歉，我可能还是不想考虑在软件里植入广告这样的形式，感觉像是破坏了初衷_(:з」∠)_
总之按次收费以后肯定会有的，但不会是马上

**Comment by PantsuDango** [comment]
关于你提到的：
1. 支持自定义url
2. 可以添加、编辑识别框及其内容
3. 支持导出工程文件

以上功能已更新并发布于 [Ver4.5.4](https://github.com/PantsuDango/Dango-Translator/releases/tag/Ver4.5.4) 版本，请更新后体验
详见 [B站动态](https://www.bilibili.com/opus/814141966142930996?spm_id_from=333.999.0.0)
