### ISSUE TITLE
关于新漫画翻译功能的问题

### ISSUE THREAD

**Issue by MuFeng086** [PantsuDango/Dango-Translator#123]
第一次试用，发现文本识别、再渲染等对于粗体描边的字体识别率并不怎么好。
如果说这对它而言难度太过还可以理解的话，那么渲染时全挤在一团的问题也是个问题，同时，其识别的文本框范围也存在误判。
虽然这个很明显比正常漫画的识别处理难度要大，不过还是希望可以做得更好吧。
<img width="1080" alt="Snipaste_2023-06-28_10-31-09" src="https://github.com/PantsuDango/Dango-Translator/assets/88829187/709a80eb-e97b-472f-b1ae-4a4ad784cd5e">
<img width="902" alt="Snipaste_2023-06-28_10-33-00" src="https://github.com/PantsuDango/Dango-Translator/assets/88829187/73e03af3-bdd6-49ca-8f14-c74a72ca5cb0">

**Comment by PantsuDango** [comment]
我觉得这个是翻译，chatgpt的问题导致的。我会要求gpt按照既定格式返给我，因为漫画是一页很多句子，每个句子要单独翻译，但是gpt不一定能保证它100%的按照我要求的格式给我，他有时候会合并到一起，就会出现你看到的这样的情况。
你可以试试换一家其他翻译源，比如私人团子重新翻译试试。
关于gpt可能会挤在一起翻译不按既定格式的问题，我本周内会研究怎么催眠调教去解决。
总之，我会尽快优化。
另外，希望你可以贴上你觉得识别效果不好的图，我这边也试试是识别不好还是翻译的问题，非常感谢~

**Comment by PantsuDango** [comment]
您提高的问题已优化，更新并发布于 [Ver4.5.4](https://github.com/PantsuDango/Dango-Translator/releases/tag/Ver4.5.4) 版本，请更新后体验
详见 [B站动态](https://www.bilibili.com/opus/814141966142930996?spm_id_from=333.999.0.0)
