### ISSUE TITLE
希望支持转发API

### ISSUE THREAD

**Issue by hubery055** [PantsuDango/Dango-Translator#124]
原版API有诸多不变，希望能支持三方转发API，谢谢

**Comment by PantsuDango** [comment]
你说的是chatgpt吧？自定义请求地址，已在开发计划中，本周内会发布此更新




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 上午10:20
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 希望支持转发API (Issue #124)





 
原版API有诸多不变，希望能支持三方转发API，谢谢

**Comment by PantsuDango** [comment]
此功能已更新并发布于 [Ver4.5.4](https://github.com/PantsuDango/Dango-Translator/releases/tag/Ver4.5.4) 版本，请更新后体验
详见 [B站动态](https://www.bilibili.com/opus/814141966142930996?spm_id_from=333.999.0.0)
