### ISSUE TITLE
[Feature Request] 希望能覆盖Magpie

### ISSUE THREAD

**Issue by maple5233** [PantsuDango/Dango-Translator#129]
https://github.com/Blinue/Magpie

预期行为：
使用Magpie全屏后，团子翻译器仍在最上层

**Comment by PantsuDango** [comment]
详见附件配图，在设置–功能设定–其他里，把全屏置顶的开关打开即可。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月5日(周六) 晚上7:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] [Feature Request] 希望能覆盖Magpie (Issue #129)




 
https://github.com/Blinue/Magpie
 
预期行为：
 使用Magpie全屏后，团子翻译器仍在最上层

**Comment by PantsuDango** [comment]
这里也有详细教程，https://dango-docs.ap-sh.starivercs.cn/#/4.0/basic/else?id=%e5%85%a8%e5%b1%8f%e7%bf%bb%e8%af%91

**Comment by maple5233** [comment]
> 详见附件配图，在设置–功能设定–其他里，把全屏置顶的开关打开即可。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月5日(周六) 晚上7:54 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [PantsuDango/Dango-Translator] [Feature Request] 希望能覆盖Magpie (Issue #129) https://github.com/Blinue/Magpie 预期行为： 使用Magpie全屏后，团子翻译器仍在最上层 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

实测这个打开了还是无法覆盖Magpie，是我Magpie配置不对吗？
