### ISSUE TITLE
在更改自定义api接口地址后， 无法正常翻译

### ISSUE THREAD

**Issue by Scarlet0326** [PantsuDango/Dango-Translator#130]
[2023-09-02 20:53:04,792][translator\api.py-line:419][ERROR]
Traceback (most recent call last):
  File "translator\api.py", line 356, in chatgpt
  File "json\__init__.py", line 357, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by PantsuDango** [comment]
看起来这是你的post请求失败，返回的resp不是json结构导致的，你可以直接打印你的resp出来看看是什么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月2日(周六) 晚上11:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 在更改自定义api接口地址后， 无法正常翻译 (Issue #130)




 
[2023-09-02 20:53:04,792][translator\api.py-line:419][ERROR]
 Traceback (most recent call last):
 File "translator\api.py", line 356, in chatgpt
 File "json_init_.py", line 357, in loads
 File "json\decoder.py", line 337, in decode
 File "json\decoder.py", line 355, in raw_decode
 json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Scarlet0326** [comment]
如何打印resp

**Comment by Scarlet0326** [comment]
[OpenKEY.Cloud](https://openkey.cloud/) 是一个 OpenAI API 反代服务，这是我使用的接口地址

**Comment by PantsuDango** [comment]
你要确定你的反代地址是可连通且完整的，检查你的路由地址是否也加上了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月2日(周六) 晚上11:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 在更改自定义api接口地址后， 无法正常翻译 (Issue #130)




 
OpenKEY.Cloud 是一个 OpenAI API 反代服务，这是我使用的接口地址

**Comment by Scarlet0326** [comment]
我本人是在国外，就没用代理地址

**Comment by Scarlet0326** [comment]
之前使用原openai的接口地址，是可以正常翻译
但是换了接口地址就出现上述问题了

**Comment by PantsuDango** [comment]
我知道你是改的api地址，我的意思是，你要确保你的api地址可用，且注意你是否填写了完整的路由地址



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月2日(周六) 晚上11:44
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 在更改自定义api接口地址后， 无法正常翻译 (Issue #130)




 
之前使用原openai的接口地址，是可以正常翻译
 但是换了接口地址就出现上述问题了

**Comment by Scarlet0326** [comment]
刚刚做了一些更改，现在可以成功翻译，但是耗时有点久，想问下有什么方法加快吗？

**Comment by PantsuDango** [comment]
没有办法，你的反代快就快，这取决于你的反代



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月3日(周日) 凌晨0:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 在更改自定义api接口地址后， 无法正常翻译 (Issue #130)




 
刚刚做了一些更改，现在可以成功翻译，但是耗时有点久，想问下有什么方法加快吗？

**Comment by Scarlet0326** [comment]
好的

**Comment by RoadToNowhereX** [comment]
你好，我也遇到了相同的问题，我的API接口地址在另外几个软件上测试都能正常使用，但是用团子翻译器就会报Expecting value: line 1 column 1 (char 0)，请问你是怎么解决的？

**Comment by PantsuDango** [comment]
是不是没加&nbsp;/v1/chat/completions，比如你只填写了&nbsp;https://api.openai.com 的域名，没加接口路由。
举个第三方接口的完整填写例子：https://api.aiguoguo199.com/v1/chat/completions




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月18日(星期三) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 在更改自定义api接口地址后， 无法正常翻译 (Issue #130)





 
你好，我也遇到了相同的问题，我的API接口地址在另外几个软件上测试都能正常使用，但是用团子翻译器就会报Expecting value: line 1 column 1 (char 0)，请问你是怎么解决的？

**Comment by RoadToNowhereX** [comment]
> 是不是没加&nbsp;/v1/chat/completions，比如你只填写了&nbsp;https://api.openai.com 的域名，没加接口路由。 举个第三方接口的完整填写例子：https://api.aiguoguo199.com/v1/chat/completions
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PantsuDango/Dango-Translator" ***@***.***&gt;; 发送时间:&nbsp;2023年10月18日(星期三) 下午4:32 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [PantsuDango/Dango-Translator] 在更改自定义api接口地址后， 无法正常翻译 (Issue #130) 你好，我也遇到了相同的问题，我的API接口地址在另外几个软件上测试都能正常使用，但是用团子翻译器就会报Expecting value: line 1 column 1 (char 0)，请问你是怎么解决的？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

还真是，多谢
