### ISSUE TITLE
能否增加一个谷歌翻译

### ISSUE THREAD

**Issue by nowata** [PantsuDango/Dango-Translator#133]
是否可以增加一个谷歌翻译的选项呢，在不少的情况下谷歌翻译还是具有一定的准确度的

**Comment by PantsuDango** [comment]
你好，谷歌翻译在中国大陆没法使用了，需要vpn才可以，其私人api的注册还需要国外的信用卡，并不方便所以去掉了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 晚上10:10
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 能否增加一个谷歌翻译 (Issue #133)




 
是否可以增加一个谷歌翻译的选项呢，在不少的情况下谷歌翻译还是具有一定的准确度的

**Comment by nowata** [comment]
或者弄个deepl的api选项？

**Comment by PantsuDango** [comment]
不太记得了，不过去掉肯定是因为它不能用了。不好意思，我不太想加回来，因为它限制太多了，不是很方便



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 晚上10:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 能否增加一个谷歌翻译 (Issue #133)




 
就是因为常用梯子才想询问一下能否加回来，就单纯的加个公共翻译的选项这样的。或者能告知提供一下以前的哪个版本可以使用谷歌翻译嘛？

**Comment by PantsuDango** [comment]
私人翻译添加deepl也是一样的，因为它是海外的，且不免费(其他私人翻译都有每月免费额度)
，使用起来不仅依赖vpn，注册还需要海外信用卡，就算接入基本上绝大多用户都是没法用上的，所以没有考虑接入。


接入新的私人翻译源，需要满足两个原则。
1. 免费可以用
2. 大部分人都可以方便用得上

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月11日(周三) 晚上11:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 能否增加一个谷歌翻译 (Issue #133)




 
或者弄个deepl的api选项？

**Comment by sqq135** [comment]
想问下，因为经常用沉浸式翻译（浏览器插件），感觉谷歌和微软是两个最好用的，还不用登录，为什么团子一个不需登录的都没有啊？

**Comment by C4a15Wh** [comment]
您如果需要开箱即用的翻译服务，可以试试翻译器内置的团子翻译，不过效果可能较差。

**Comment by sqq135** [comment]
因为不在国内，所以延迟太高了，还经常失效，算是不可用状态

**Comment by C4a15Wh** [comment]
那建议挂一下回国VPN，翻译器本身服务范围就大陆这块。

**Comment by sqq135** [comment]
我用的不多，腾讯就够用的了，所以只是好奇。我常用的第三方翻译软件，基本都支持谷歌和微软翻译，特别是微软，不用额外设置很方便，这些软件也都是免费的。其中开源的也不少见，想来成本也不太高（金钱方面）。比如这个https://[copytranslator.gitee.io](https://copytranslator.gitee.io/)/，甚至可以谷歌镜像。我觉得开箱即用这个体验就比较好了。

**Comment by PantsuDango** [comment]
你好，是这样的。因为谷歌和微软翻译，在国内是无法正常使用的，谷歌翻译也已经宣布放弃国内的调用了，所以国内想直连使用谷歌翻译的体验是很糟糕的，往往需要挂代理很麻烦，且调用速度慢很不稳定。
团子在很早的版本就是支持谷歌和bing翻译的，但是由于以上原因所以移除了。
可能因为您在国外，所以调用没有稳定性的问题。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月2日(星期六) 下午5:38
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 能否增加一个谷歌翻译 (Issue #133)





 
我用的不多，腾讯就够用的了，所以只是好奇。我常用的第三方翻译软件，基本都支持谷歌和微软翻译，特别是微软，不用额外设置很方便，这些软件也都是免费的。其中开源的也不少见，想来成本也不太高（金钱方面）。比如这个https://copytranslator.gitee.io/，甚至可以谷歌镜像。我觉得开箱即用这个体验就比较好了。

**Comment by sqq135** [comment]
明白了，感谢解惑。您也实在太客气了，已经用上5.0了，期待接下来的更新。
