### ISSUE TITLE
能否提供一个本地llama的接口

### ISSUE THREAD

**Issue by Chachkey15** [PantsuDango/Dango-Translator#136]

**Comment by PantsuDango** [comment]
这个接入您可以fork源码来实现




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月14日(星期四) 下午2:49
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 能否提供一个本地llama的接口 (Issue #136)
