### ISSUE TITLE
发送验证码邮件失败了

### ISSUE THREAD

**Issue by lzslab** [PantsuDango/Dango-Translator#137]
你好，点击获取验证码按钮后，弹出弹窗：

发送验证码邮件失败了！
SendEmailError
请直接联系团子解决

**Comment by PantsuDango** [comment]
你好，这个是网络问题，你连不上团子的服务器。检查下有没有开梯子啊加速器什么的影响网络，或者你是不是海外党、校园网之类的。
可以试试使用手机流量作为热点





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月18日(周一) 下午3:41
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 发送验证码邮件失败了 (Issue #137)




 
你好，点击获取验证码按钮后，弹出弹窗：
 
发送验证码邮件失败了！
 SendEmailError
 请直接联系团子解决

**Comment by lzslab** [comment]
好的，谢谢。我检查一下
