### ISSUE TITLE
软件报毒

### ISSUE THREAD

**Issue by aiiibolo** [PantsuDango/Dango-Translator#14]
![Snipaste_2020-07-01_09-32-37](https://user-images.githubusercontent.com/50828181/86193188-e2499280-bb7d-11ea-8c71-469d66b2ad04.png)

**Comment by PantsuDango** [comment]
杀毒软件就是最大的病毒...关闭杀毒，从我做起

**Comment by crhong** [comment]
![2020-07-05_014455](https://user-images.githubusercontent.com/16818149/86518192-0baa3d00-be62-11ea-956b-24092fbcf743.jpg)
这是知名在线扫毒网站virus total的扫描结果，57个引擎无一报毒，windows defender基本上会把大部分从浏览器下载的exe文件当成威胁拦截要你删除，关掉或者换其他杀软吧

**Comment by aiiibolo** [comment]
> 杀毒软件就是最大的病毒...关闭杀毒，从我做起
