### ISSUE TITLE
错误：pip的依赖关系解析程序当前没有考虑所有已安装的程序包。这种行为是以下依赖冲突的根源。

### ISSUE THREAD

**Issue by a564m** [PantsuDango/Dango-Translator#141]
错误：pip的依赖关系解析程序当前没有考虑所有已安装的程序包。这种行为是以下依赖冲突的根源。

lida 0.0.10需要万花筒，但没有安装。

jupyter服务器1.24.0需要anyio＜4，＞＝3.1.0，但您有不兼容的anyio 4.2.0。

tensorboard 2.15.1要求protobuf<4.24，>=3.19.6，但您有不兼容的protobuf 4.25.2。

tensorflow元数据1.14.0需要absl py<2.0.0，>=0.9，但您有不兼容的absl py 2.1.0。

tensorflow元数据1.14.0需要protobuf＜4.21，＞＝3.20.3，但您有不兼容的protobuf 4.25.2。

tensorflow概率0.22.0需要键入<4.6.0的扩展名，但您有不兼容的4.9.0扩展名。

torchhavet2.1.0+cu121需要torch==2.1.0，但您有不兼容的torch2.1.2+cu121。

torchdata 0.7.0需要torch==2.1.0，但您有不兼容的torch 2.1.2+cu121。

torchtext 0.16.0需要torch==2.1.0，但您有不兼容的torch 2.1.2+cu121。

错误：pip的依赖关系解析程序当前没有考虑所有已安装的程序包。这种行为是以下依赖冲突的根源。

ipython 7.34.0需要jedi>=0.16，但没有安装。

lida 0.0.10需要万花筒，但没有安装。

llmx 0.0.15a0需要cohere，但未安装。

llmx 0.0.15a0需要openai，但未安装。

llmx 0.0.15a0需要tiktoken，但没有安装。

bigframes 0.19.2要求pandas<2.1.4，>=1.5.0，但您有pandas 2.2.0，这是不兼容的。

gcsfs 2023.6.0需要fsspec==2023.6.0，但您有不兼容的fsspec 2023.12.2。

googlecolab1.0.0需要pandas==1.5.3，但是pandas2.2.0是不兼容的。

jupyter服务器1.24.0需要anyio＜4，＞＝3.1.0，但您有不兼容的anyio 4.2.0。

tensorboard 2.15.1要求protobuf<4.24，>=3.19.6，但您有不兼容的protobuf 4.25.2。

tensorflow元数据1.14.0需要absl py<2.0.0，>=0.9，但您有不兼容的absl py 2.1.0。

tensorflow元数据1.14.0需要protobuf＜4.21，＞＝3.20.3，但您有不兼容的protobuf 4.25.2。

tensorflow概率0.22.0需要键入<4.6.0的扩展名，但您有不兼容的4.9.0扩展名。

torchhavet2.1.0+cu121需要torch==2.1.0，但您有不兼容的torch2.1.2+cu121。

torchdata 0.7.0需要torch==2.1.0，但您有不兼容的torch 2.1.2+cu121。
![7C4`ZE 5N7G7Q3X7(6T{ULB](https://github.com/PantsuDango/Dango-Translator/assets/155218424/dfe4de0f-e0f3-47ea-945d-1fa36bf84a26)
![ZCX5SZDHLX 8 8JBIZ2 @YF](https://github.com/PantsuDango/Dango-Translator/assets/155218424/65b3fa79-2adc-4703-a677-04595958f13c)

torchtext 0.16.0需要torch==2.1.0，但您有不兼容的torch 2.1.2+cu121。

![7C4`ZE 5N7G7Q3X7(6T{ULB](https://github.com/PantsuDango/Dango-Translator/assets/155218424/dfe4de0f-e0f3-47ea-945d-1fa36bf84a26)
![ZCX5SZDHLX 8 8JBIZ2 @YF](https://github.com/PantsuDango/Dango-Translator/assets/155218424/65b3fa79-2adc-4703-a677-04595958f13c)
这些错误怎么卸载错的,安装正确的啊，对这些真的完全搞不懂┭┮﹏┭┮，有没有视频或者步骤看看啊

**Comment by PantsuDango** [comment]
建议搭一个干净的新环境来装

**Comment by a564m** [comment]
> 建议搭一个干净的新环境来装

但是我完全不会弄这些，用这个也是看网上只会点开始让他自己去缓存好而已。。搭和新环境什么的完全听不懂

**Comment by PantsuDango** [comment]
为什么要去跑源码，是希望做什么自定义修改么




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月26日(星期五) 下午4:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 错误：pip的依赖关系解析程序当前没有考虑所有已安装的程序包。这种行为是以下依赖冲突的根源。 (Issue #141)





  
建议搭一个干净的新环境来装
  
但是我完全不会弄这些，用这个也是看网上只会点开始让他自己去缓存好而已。。搭和新环境什么的完全听不懂

**Comment by PantsuDango** [comment]
你直接用安装包运行就好了，不用去纠结折腾源码的，不理解您在使用安装版遇到的具体问题是什么，这里有个**QQ群887228946** ，专门解决一切翻译器相关的问题，可以来这里寻求帮助。

[正式版安装包下载地址](https://translator.dango.cloud/)
