### ISSUE TITLE
是否考虑使gpt接口适用于text-generation-webui？

### ISSUE THREAD

**Issue by beavermarine** [PantsuDango/Dango-Translator#142]
目前tgw使用和gpt相同的api，但是没有api_key，留空会报错。鉴于一些可以本地使用的模型在翻译水平上已经达到了机翻程度，希望可以适配tgw。

**Comment by PantsuDango** [comment]
我已经接了tgw，但是没开放出来，你要试试么，可以直接戳我qq




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月27日(星期六) 晚上11:51
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 是否考虑使gpt接口适用于text-generation-webui？ (Issue #142)





 
目前tgw使用和gpt相同的api，但是没有api_key，留空会报错。鉴于一些可以本地使用的模型在翻译水平上已经达到了机翻程度，希望可以适配tgw。

**Comment by PantsuDango** [comment]
这是一个单独接入了tgw的版本 [EOS下载地址](https://dango-static.eos-shanghai-2.cmecloud.cn/patches/dango_translator/DangoTranslatorVer5.1.0-Beta.zip)

你可以在如图所示的位置开启调用
![{71C1C2BD-7039-4a9f-AE20-41B32D0CFC61}](https://github.com/PantsuDango/Dango-Translator/assets/61474148/8c79d08b-9ecd-4872-b817-430d2c134496)

**Comment by beavermarine** [comment]
抱歉这几天没上GitHub。cpu：12400 显卡：3060-12g 内存32g。使用tgw加载sakura-13b-lnovel-v0.9-Q4KM_awq4bit.gguf模型 可以正常调用tgw。翻译速度大概为10token每秒。遇见大量语气词的内容时会出现复述，其他翻译内容偶尔抽风不过语句通顺度要好于机翻，多谢您的分享。
