### ISSUE TITLE
百度OCR由于未知原因无法设定识别方向

### ISSUE THREAD

**Issue by time-of-flowers** [PantsuDango/Dango-Translator#143]
如题，是个坑
![屏幕截图 2024-01-30 201204](https://github.com/PantsuDango/Dango-Translator/assets/87291086/eb481bc0-e2a8-404f-9979-4faca02e4e9a)
这是原文

?りをて:も害つやつ危奪じるにをんえ々力な加人魔
这是竖向识别

な加人魔るやつ，も，り々に危害を力を奪って
这是横向识别

反正就是不按照人类的阅读顺序来是吧

**Comment by PantsuDango** [comment]
由于百度OCR我们调用的是通用识别接口，这个接口并不会返回文字块的坐标信息，所以是无法准确定位文字顺序的。
如果你有竖向识别，漫画识别的需求，还是建议直接使用我们开发优化过的，漫画翻译模块




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月30日(星期二) 晚上8:14
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 百度OCR由于未知原因无法设定识别方向 (Issue #143)





 
如题，是个坑
 2024-01-30.201204.png (view on web)
 这是原文
 
?りをて:も害つやつ危奪じるにをんえ々力な加人魔
 这是竖向识别
 
な加人魔るやつ，も，り々に危害を力を奪って
 这是横向识别
 
反正就是不按照人类的阅读顺序来是吧
