### ISSUE TITLE
完全版5.1.7beta版运行卡的要死

### ISSUE THREAD

**Issue by Hanabi155** [PantsuDango/Dango-Translator#147]
明明ram占用只有60~70左右，然而无论是拖动翻译框、文字框选范围还是在设置里切换选项这些操作都卡的要命……

**Comment by Hanabi155** [comment]
oh不简易版也一模一样……

**Comment by PantsuDango** [comment]
近期会发布正式版，此问题将得到解决

**Comment by PantsuDango** [comment]
卡的问题已经修复了，可在 [官网](https://translator.dango.cloud/) 下载最新版本解决
