### ISSUE TITLE
今天才发现这款宝藏软件，不过翻译的时候一直闪怎么办呀

### ISSUE THREAD

**Issue by codeNiuMa** [PantsuDango/Dango-Translator#148]
![PixPin_2024-05-14_10-14-20](https://github.com/PantsuDango/Dango-Translator/assets/101323354/6b85e745-2226-4e9f-bf4f-795e2c3cf60c)
如图，安装的5.1.7-Beta，翻译模型使用的是阿里云机器翻译，本地OCR

**Comment by PantsuDango** [comment]
你把 翻译框挪开，不要和范围框重叠就好了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月14日(星期二) 上午10:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 今天才发现这款宝藏软件，不过翻译的时候一直闪怎么办呀 (Issue #148)





 
PixPin_2024-05-14_10-14-20.gif (view on web)
 如图，安装的5.1.7-Beta，翻译模型使用的是阿里云机器翻译，本地OCR
