### ISSUE TITLE
建议翻译窗口加入文字自动换行功能

### ISSUE THREAD

**Issue by crhong** [PantsuDango/Dango-Translator#15]
RT，在调整了翻译窗口大小后，遇到翻译文本量较多时文字会显示不完整跑出了窗口界面，这时要把窗口拉得很长才能看到完整文字，重启翻译器后不调整窗口大小则没问题，建议加入文字自动换行功能，在调整了翻译窗口大小的情况下能生效

**Comment by PantsuDango** [comment]
3.4版本就是自带自动换行，和根据文字内容自动适配文本框，我不知道你为什么会遇到这样的情况，方便的话请加我QQ 我也好奇你是为什么不会触发自动换行

**Comment by crhong** [comment]
> 3.4版本就是自带自动换行，和根据文字内容自动适配文本框，我不知道你为什么会遇到这样的情况，方便的话请加我QQ 我也好奇你是为什么不会触发自动换行

我发现即使重启翻译器不调整窗口大小还是会发生文字显示不全的情况，不知道是否和改变了翻译文字大小有关，但这不是每次都能复现，可能是偶发性bug

**Comment by PantsuDango** [comment]
这肯定是存在bug的，我想试图找出问题出在哪------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;crhong&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年7月9日(星期四) 凌晨2:13
收件人:&nbsp;&quot;PantsuDango/Dango-Translator&quot;<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;&quot;胖次团子&quot;<394883561@qq.com&gt;;&quot;Comment&quot;<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 建议翻译窗口加入文字自动换行功能 (#15)

**Comment by PantsuDango** [comment]
此问题在最新版本已修复
