### ISSUE TITLE
无法关闭图片翻译试用开关，被强迫使用在线OCR

### ISSUE THREAD

**Issue by 1434015845** [PantsuDango/Dango-Translator#150]
已多次确认并尝试过重装ocr和软件，试用开关的部分始终显示为开。
![image](https://github.com/PantsuDango/Dango-Translator/assets/41281165/1d2b100d-9186-4aa2-9986-9f07b0ae8e22)

**Comment by 1434015845** [comment]
![image](https://github.com/PantsuDango/Dango-Translator/assets/41281165/b0371d9e-6dbd-43ef-9a11-4c1ea73a3d6e)

**Comment by 1434015845** [comment]
![image](https://github.com/PantsuDango/Dango-Translator/assets/41281165/21816a6a-80d2-4298-b73e-e39eebdeedc9)

**Comment by PantsuDango** [comment]
图片翻译这里的功能 和你截图的本地OCR没啥关系，本地OCR是给即时翻译游戏用的。漫画翻译只能走云端的漫画OCR
