### ISSUE TITLE
翻译源打开后如何使用

### ISSUE THREAD

**Issue by Bearlele** [PantsuDango/Dango-Translator#152]
翻译源已经打开了GPT，测试正常已启用，但识别设定内只有在线OCR本地OCRH和百度OCR，我该如何使用GPT进行OCR翻译？

**Comment by PantsuDango** [comment]
gpt不能用于文字识别，你得用ocr技术把要翻译的文字识别出来，再交给翻译源翻译成中文，gpt是用于翻译的，不是识别的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年8月16日(周五) 下午4:59
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 翻译源打开后如何使用 (Issue #152)




 
翻译源已经打开了GPT，测试正常已启用，但识别设定内只有在线OCR本地OCRH和百度OCR，我该如何使用GPT进行OCR翻译？
