### ISSUE TITLE
希望添加免费大模型 翻译源Siliconflow

### ISSUE THREAD

**Issue by littledgg** [PantsuDango/Dango-Translator#153]
官方定价
https://siliconflow.cn/pricing
官方API文档
https://docs.siliconflow.cn/docs/4-api%E8%B0%83%E7%94%A8
在看沉浸式翻译时看见的，竟然有免费的大模型使用，手机号注册即可使用，试了一下可以翻译日文，不过不清楚翻译galgame文本合不合适，不行的话就close吧

**Comment by PantsuDango** [comment]
你好，我看了关于你说的&nbsp;Siliconflow，它本身就支持 OpenAI 协议的，所以你可以直接用 团子里的 chatgpt 那个翻译源，把 api 地址改为Siliconflow的地址&nbsp;https://api.siliconflow.cn&nbsp;，然后把密钥填上&nbsp;Siliconflow 的密钥，模型就用&nbsp;Siliconflow 列出的免费模型，你就可以使用了，他们都是兼容的。
如有进一步的疑问，可以直接来交流群&nbsp;835628840&nbsp;找我，我是群主




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月26日(星期一) 下午5:19
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 希望添加免费大模型 翻译源Siliconflow (Issue #153)





 
官方定价
 https://siliconflow.cn/pricing
 
在看沉浸式翻译时看见的
