### ISSUE TITLE
希望解决windows defender 提示木马问题

### ISSUE THREAD

**Issue by susyimes** [PantsuDango/Dango-Translator#17]
![微信图片_20200713115903](https://user-images.githubusercontent.com/15085918/87269617-449c7e80-c500-11ea-9b7e-c1dff0136ea6.png)

**Comment by susyimes** [comment]
OCR通常都会引起WD报毒是通病。

**Comment by PantsuDango** [comment]
应该不是OCR导致的，是我调用了windows的api去注册全局快捷键，导致防火墙认为我调用了系统权限级




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月13日(星期一) 中午12:05
收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 希望解决windows defender 提示木马问题 (#17)





 
OCR服务通常都会引起WD报毒是通病。
