### ISSUE TITLE
多屏情况下只有主屏能选定区域

### ISSUE THREAD

**Issue by mzspeedwolf** [PantsuDango/Dango-Translator#20]
把翻译窗口移动到别的屏幕区域，翻译选定区域也不随着窗口所在屏幕而变更，始终只能在主屏选择。
希望增加这项功能，感谢！

**Comment by PantsuDango** [comment]
因为每个启动程序都只对应它目录的config下的配置，所以如果你只是在同一个文件夹内对同一个应用多开，他们始终都共享同一个配置文件。你需要完整地以文件夹为单位复制多份，才可以实现多开，他们各自用自己的配置文件，互不影响

**Comment by mzspeedwolf** [comment]
我是指比如有4个显示器，程序只能在主屏上选择翻译区域，别的屏幕上就无法选择翻译区域了

**Comment by PantsuDango** [comment]
4个屏幕...是土豪的需求！我之前都没想过这样的情况 因为我只有一个屏幕 我看看吧 国庆会更新一次 记住了_(:з」∠)_

**Comment by mzspeedwolf** [comment]
我注意到config/settin.json里的"range"值是翻译选定范围，虽然可以手动指定位置，但进行选定的时候只有主屏暗屏响应了。
感谢回复

**Comment by PantsuDango** [comment]
是滴 ~ 因为我都是一个屏幕开发的 ...所以当初根本没想过这样的情况 我会尝试修复看看 意见我收到了~

**Comment by azumia-azu** [comment]
修改desktopRect取值方式，双屏环境已经可以正常框选了[#21 pull](https://github.com/PantsuDango/Dango-Translator/pull/21)

**Comment by PantsuDango** [comment]
新版本已修复此问题
