### ISSUE TITLE
v3.5版本修改密码功能在哪里？

### ISSUE THREAD

**Issue by AngelLiang** [PantsuDango/Dango-Translator#22]
RT。

版本：v3.5

我都不明白为什么要有注册功能，有就算了，还没修改密码功能。先不说同步后各种api key可能会泄漏的问题，到时被别人拿账号密码撞库就好笑了。

**Comment by PantsuDango** [comment]
联系我帮你修改 目前没做修改密码的功能=。=




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月6日(星期三) 上午9:27
收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] v3.5版本修改密码功能在哪里？ (#22)





 
RT。
 
版本：v3.5
 
我都不明白为什么要有注册功能还没修改密码功能，先不说同步后各种api key可能会泄漏的问题，到时被别人拿账号密码撞库就好笑了。

**Comment by AngelLiang** [comment]
@PantsuDango 算了，请尽早考虑修改密码功能，最基本的请求。

**Comment by PantsuDango** [comment]
好的
