### ISSUE TITLE
请问这个gituhub代码运行时出现ModuleNotFoundError: No module named 'Translate'怎么解决呢

### ISSUE THREAD

**Issue by ZhangRenkai** [PantsuDango/Dango-Translator#23]

**Comment by PantsuDango** [comment]
你源码文件没下全吧？Translate.py是自定义的模块，也在根目录里。这个报错就是没找到那个文件，可以通过我的qq直接联系我会比较方便呢



---原始邮件---
发件人: "ZhangRenkai"<notifications@github.com&gt;
发送时间: 2021年1月16日(周六) 下午4:41
收件人: "PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [PantsuDango/Dango-Translator] 请问这个gituhub代码运行时出现ModuleNotFoundError: No module named 'Translate'怎么解决呢 (#23)

**Comment by lyu-kun** [comment]
如果这个文件名称是translate.py的话，可以考虑改为Translate.py，或许能解决这个问题

**Comment by Wltamilku** [comment]
可能是文件名的问题，虽然晚了|°3°|
