### ISSUE TITLE
关于团子翻译器在异形屏环境下的Bug

### ISSUE THREAD

**Issue by Cwlrin** [PantsuDango/Dango-Translator#26]
个人的使用环境：双屏，主屏的屏幕分辨率是 3440 * 1440，副屏的屏幕分辨率为1080 * 1920。

启用团子翻译器的时候会出现团子翻译器突然异味的情况（拖动团子翻译器的时候出现，翻译框突然频闪，瞬移至屏幕边框位置再瞬移回来，甚至有翻译框跳出屏幕无法拉回的情况）

打开查询错误用.exe后，登录后小黑框出现 `Unknown property background-size` 字样。

拖动翻译器时，出现以下类型信息：

```
QWindowsWindow::setGeometry: Unable to set geometry 800x120-541+1061 (frame: 800x120-541+1061) on QWidgetWindow/"MainInterfaceClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1000x150-541+1061 (frame: 1000x150-541+1061) margins: 0, 0, 0, 0 minimum size: 16x22 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=16,22 maxtrack=0,0)
QWindowsWindow::setGeometry: Unable to set geometry 1000x150+636+630 (frame: 1000x150+636+630) on QWidgetWindow/"MainInterfaceClassWindow" on "\\.\DISPLAY4". Resulting geometry: 800x120+636+630 (frame: 800x120+636+630) margins: 0, 0, 0, 0 minimum size: 16x25 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=16,25 maxtrack=0,0)
````

![image](https://user-images.githubusercontent.com/55187695/109004956-612ea500-76e4-11eb-8e1f-529c0f18fa0b.png)

之前使用1920 * 1080和1080 * 1920的双屏环境时无此Bug，故推测此 Bug 可能和异形屏的分辨率有关，希望团子大大可以排查一下修复，谢谢团子啦！！

**Comment by PantsuDango** [comment]
非常感谢你提供这么详细的bug说明，啊~ 是有钱人才会遇到的bug~ 你的描述很详细了，但是我需要一个高分辨率的屏幕复现才好修复好！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 晚上9:12
收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 关于团子翻译器在异形屏环境下的Bug (#26)





 
个人的使用环境：双屏，主屏的屏幕分辨率是 3440 * 1440，副屏的屏幕分辨率为1080 * 1920。
 
启用团子翻译器的时候会出现团子翻译器突然异味的情况（拖动团子翻译器的时候出现，翻译框突然频闪，瞬移至屏幕边框位置再瞬移回来，甚至有翻译框跳出屏幕无法拉回的情况）
 
打开查询错误用.exe后，登录后小黑框出现 Unknown property background-size 字样。
 
拖动翻译器时，出现以下类型信息：
 QWindowsWindow::setGeometry: Unable to set geometry 800x120-541+1061 (frame: 800x120-541+1061) on QWidgetWindow/"MainInterfaceClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1000x150-541+1061 (frame: 1000x150-541+1061) margins: 0, 0, 0, 0 minimum size: 16x22 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=16,22 maxtrack=0,0) QWindowsWindow::setGeometry: Unable to set geometry 1000x150+636+630 (frame: 1000x150+636+630) on QWidgetWindow/"MainInterfaceClassWindow" on "\\.\DISPLAY4". Resulting geometry: 800x120+636+630 (frame: 800x120+636+630) margins: 0, 0, 0, 0 minimum size: 16x25 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=16,25 maxtrack=0,0)  

 
之前使用1920 * 1080和1080 * 1920的双屏环境时无此Bug，故推测此 Bug 可能和异形屏的分辨率有关，希望团子大大可以排查一下修复，谢谢团子啦！！

**Comment by PantsuDango** [comment]
总之非常感谢你 ~ 我会尝试在下一个3.6版本修复此问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月24日(星期三) 晚上9:12
收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 关于团子翻译器在异形屏环境下的Bug (#26)





 
个人的使用环境：双屏，主屏的屏幕分辨率是 3440 * 1440，副屏的屏幕分辨率为1080 * 1920。
 
启用团子翻译器的时候会出现团子翻译器突然异味的情况（拖动团子翻译器的时候出现，翻译框突然频闪，瞬移至屏幕边框位置再瞬移回来，甚至有翻译框跳出屏幕无法拉回的情况）
 
打开查询错误用.exe后，登录后小黑框出现 Unknown property background-size 字样。
 
拖动翻译器时，出现以下类型信息：
 QWindowsWindow::setGeometry: Unable to set geometry 800x120-541+1061 (frame: 800x120-541+1061) on QWidgetWindow/"MainInterfaceClassWindow" on "\\.\DISPLAY1". Resulting geometry: 1000x150-541+1061 (frame: 1000x150-541+1061) margins: 0, 0, 0, 0 minimum size: 16x22 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=16,22 maxtrack=0,0) QWindowsWindow::setGeometry: Unable to set geometry 1000x150+636+630 (frame: 1000x150+636+630) on QWidgetWindow/"MainInterfaceClassWindow" on "\\.\DISPLAY4". Resulting geometry: 800x120+636+630 (frame: 800x120+636+630) margins: 0, 0, 0, 0 minimum size: 16x25 MINMAXINFO maxSize=0,0 maxpos=0,0 mintrack=16,25 maxtrack=0,0)  

 
之前使用1920 * 1080和1080 * 1920的双屏环境时无此Bug，故推测此 Bug 可能和异形屏的分辨率有关，希望团子大大可以排查一下修复，谢谢团子啦！！

**Comment by luojunyuan** [comment]
似乎是DPI感知变化没处理的问题，团子是对不同屏幕DPI感知有响应的。win10下两个显示器调整为相同DPI就不会出现这个问题。
相关链接
https://stackoverflow.com/questions/54307407/why-am-i-getting-qwindowswindowsetgeometry-unable-to-set-geometry-warning-wit
https://bugreports.qt.io/browse/QTBUG-84090
不清楚有没有较好的解决方案

**Comment by WWW5911** [comment]
目前使用7/4发布的3.6版，也是有相同的状况
我本身是使用2个1920*1080的屏幕
![image](https://i.imgur.com/IHiLo1e.gif)

**Comment by timkayhou** [comment]
同样情况。双屏 3440 * 1440 + 1080 * 1920

**Comment by PantsuDango** [comment]
这个问题一直被我搁置了...不好意思，看来得好好研究一下qwq




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月4日(星期五) 晚上8:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 关于团子翻译器在异形屏环境下的Bug (#26)





 
同样情况。双屏 3440 * 1440 + 1080 * 1920
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PantsuDango** [comment]
新版本已修复，close the issu
