### ISSUE TITLE
作者 你软件“出名了”

### ISSUE THREAD

**Issue by fansi2020** [PantsuDango/Dango-Translator#27]
bing搜索一下团子翻译器 排行第一的链接是华君软件园，到处都是盗版

**Comment by PantsuDango** [comment]
唉，我知道这个现象，但是我没有办法阻止。。。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月15日(星期一) 上午10:57
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 作者 你软件“出名了” (#27)





 
bing搜索一下团子翻译器 排行第一的链接是华君软件园，到处都是盗版
