### ISSUE TITLE
玩游戏时，翻译器不置顶咋办，总被游戏窗口覆盖

### ISSUE THREAD

**Issue by 1481707634** [PantsuDango/Dango-Translator#29]

**Comment by PantsuDango** [comment]
游戏不可以全屏，只可以最大化或者窗口化，因为置顶是唯一的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月28日(星期天) 晚上9:27
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 玩游戏时，翻译器不置顶咋办，总被游戏窗口覆盖 (#29)

**Comment by 1481707634** [comment]
谢答，即使开了窗口化，当选择游戏窗口翻译区域时（当鼠标选择截屏区域时），还是默认游戏窗口置顶，导致只能在桌面区域截屏，照你的回答，看来游戏窗口被置顶唯一了
