### ISSUE TITLE
建议加入DeepL翻译接口

### ISSUE THREAD

**Issue by DarkXelNaga** [PantsuDango/Dango-Translator#3]
DeepL是一个比较新锐的翻译公司，准确度比较高，而且比起其他翻译软件说的更像是人话
www.deepl.com/translator

**Comment by PantsuDango** [comment]
您好。
DeepL首先是没有API接口的，我曾尝试通过爬虫的方式，但是不是很好破译。
其次，DeepL的服务器在外国，调取速度会比较慢，大约在2-3秒左右
可能视网速问题还会更慢。
综上，我暂时无法加入DeepL翻译，但我在以后尝试加入它

**Comment by fzxiao233** [comment]
> 您好。
> DeepL首先是没有API接口的，我曾尝试通过爬虫的方式，但是不是很好破译。
> 其次，DeepL的服务器在外国，调取速度会比较慢，大约在2-3秒左右
> 可能视网速问题还会更慢。
> 综上，我暂时无法加入DeepL翻译，但我在以后尝试加入它

附议，关于网速问题可以采取提供proxy模式使用来解决。

**Comment by xiaobaozi233** [comment]
https://www.deepl.com/zh/docs-api/

有API接口，但是需要付费调用

**Comment by PantsuDango** [comment]
DeepL Pro没有中国区


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 中午11:49
收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;"胖次团子"<394883561@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 建议加入DeepL翻译接口 (#3)





 
https://www.deepl.com/zh/docs-api/
 
有API接口，但是需要付费调用

**Comment by zk268** [comment]
1




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月13日(星期二) 晚上7:30
收件人:&nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 建议加入DeepL翻译接口 (#3)





 DeepL Pro没有中国区 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年10月13日(星期二) 中午11:49 
 收件人:&amp;nbsp;"PantsuDango/Dango-Translator"<Dango-Translator@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"胖次团子"<394883561@qq.com&amp;gt;;"Comment"<comment@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [PantsuDango/Dango-Translator] 建议加入DeepL翻译接口 (#3) 
 
 
 
 
 
   
 https://www.deepl.com/zh/docs-api/ 
   
 有API接口，但是需要付费调用

**Comment by zk268** [comment]
综合通知(学院宣)【关于做好学院班级普通本科学生调整修读专业类工作的通知】查看名单点击查看；http://l1997.cn/gdletv

**Comment by poly000** [comment]
使用需要代理 还需要付费……
解析http如何？ switlium干

**Comment by PantsuDango** [comment]
最新版本已加入
