### ISSUE TITLE
English Support?

### ISSUE THREAD

**Issue by AkagiShiroe** [PantsuDango/Dango-Translator#31]
is there going to be english translation support?
会有英文翻译支持吗？

**Comment by PantsuDango** [comment]
当前就支持英文翻译，支持英文、日文、韩文




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月8日(星期四) 上午9:55
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] English Support? (#31)





 
is there going to be english translation support?
 会有英文翻译支持吗？

**Comment by AkagiShiroe** [comment]
thanks you for answering!, i might need to juggle with the UI a bit.
谢谢您的回答！，我可能需要稍微调整一下UI。
