### ISSUE TITLE
 fanyi.baidu.com/v2transapi 不能翻译长句子了

### ISSUE THREAD

**Issue by afowne** [PantsuDango/Dango-Translator#34]
昨天突然发现出现，英->中，超过500个字符的长句子时，会timeout
我是在2秒调用一次，大概十次左右会出现这样的情况
timeout=5的时候会直接超时
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='fanyi.baidu.com', port=443): Read timed out. (read timeout=5)
timeout=20的时候，返回值里就没有翻译结果data，只有keywords

有人遇到类似的情况么，求教怎么解决

**Comment by PantsuDango** [comment]
请问你使用的是什么版本？私人百度翻译的话，我这边调的是 /api/trans/vip/translate，但是这个翻译接口我没有做过timeout的限制

**Comment by afowne** [comment]
> 请问你使用的是什么版本？私人百度翻译的话，我这边调的是 /api/trans/vip/translate，但是这个翻译接口我没有做过timeout的限制

不好意思，那天好像接口抽风，晚上就又正常了
