### ISSUE TITLE
3.6版本使用本地OCR时CPU占用率100%

### ISSUE THREAD

**Issue by Rakau** [PantsuDango/Dango-Translator#35]
请问如何解决？

**Comment by Rakau** [comment]
补充：是DangoOCR一直在扫描，只要扫描区域在动，占用率就100%

**Comment by PantsuDango** [comment]
如果你的识别区域是动态的，一直在变化的话，建议不要开自动模式，用手动会比较好，不然ocr会一直在识别

**Comment by Rakau** [comment]
> 如果你的识别区域是动态的，一直在变化的话，建议不要开自动模式，用手动会比较好，不然ocr会一直在识别

也只能这样了

**Comment by DemonPaean** [comment]
如果你不介意频率低点的话，可以打开app.py
在上面加上import time
然后在def ocrResultSort(ocr_result)下面加上time.sleep(1)
我试了之后cpu占用降到了40

**Comment by DemonPaean** [comment]
注意保险起见用4个空格，不要用tab

**Comment by Rakau** [comment]
谢谢，有空试试，不然CPU都吃的死死的，游戏效能下降

DemonPaean ***@***.***> 于 2021年8月19日周四 22:43写道：
