### ISSUE TITLE
[BUG] 更改 Windows 缩放时文字显示 bug

### ISSUE THREAD

**Issue by UraraChiya** [PantsuDango/Dango-Translator#36]
系统：Windows 10 20H2
软件版本：3.6.1
问题描述：设置-系统-显示-缩放与布局-更改文本、应用等项目的大小 超过 100% 时，登录界面文字将显示不全
截图：
![Snipaste_2021-07-19_14-19-47](https://user-images.githubusercontent.com/47343409/126112115-53056ff3-cf67-4629-8751-6cb48422104c.jpg)
![Snipaste_2021-07-19_14-19-14](https://user-images.githubusercontent.com/47343409/126112125-8117d664-b4e2-41ef-a5d1-f8fcf129f81c.jpg)

**Comment by PantsuDango** [comment]
目前界面的适配比例我只做到了175%，以上都不行。我已将更高的4k屏的适配加入到了更新计划了，下一个版本将会修复此问题。
