### ISSUE TITLE
OCR 錯誤，請問要怎麼解決

### ISSUE THREAD

**Issue by UNKNOWNREM** [PantsuDango/Dango-Translator#37]
已經有安裝 DangoOCR.exe 運行完成，測試工具開啟後就消失了
![image](https://user-images.githubusercontent.com/65601335/127327934-89086766-2633-49ac-b534-5b321425554d.png)

**Comment by PantsuDango** [comment]
DangoOCR.exe要保持运行，黑窗在使用过程中不可以关闭

**Comment by UNKNOWN920108** [comment]
執行中，未曾中斷
![Uploading 336FDD6B-A664-405B-B454-013A7BF38C06.jpeg…]()

**Comment by PantsuDango** [comment]
那给我看看ocr运行的黑色窗口有什么信息，保持运行使用后的

**Comment by UNKNOWN920108** [comment]
![螢幕擷取畫面 2021-07-29 131201](https://user-images.githubusercontent.com/65601335/127435705-c2c3705b-8685-4f15-ac08-1c3eade3a72a.png)

**Comment by PantsuDango** [comment]
这个是正常运行，还没运行完呢。我说的是，ocr运行完成后，通过翻译器或者测试工具去使用它的时候，如果它报错了，那个报错截图给我

**Comment by UNKNOWN920108** [comment]
![0001](https://user-images.githubusercontent.com/65601335/127492354-3b5217f3-609a-4009-b05e-07cac9fc94d5.png)
![0002](https://user-images.githubusercontent.com/65601335/127492360-33210b92-45a3-4a5f-8b4a-c4ceab8525d9.png)

**Comment by PantsuDango** [comment]
你给的是翻译器的截图，需要看运行时ocr那边黑窗的错误截图

**Comment by UNKNOWNREM** [comment]
![S__7880743](https://user-images.githubusercontent.com/65601335/127654481-7deece70-59b0-48cd-9487-522f4688e6a2.jpg)

**Comment by PantsuDango** [comment]
不是这个，是ocr运行时报错的黑窗，DangoOCR.exe。你还是直接QQ私聊我比较方便

**Comment by UNKNOWNREM** [comment]
我沒QQ帳號註冊不了
試了好幾次使用測試工具或是翻譯器，都沒出現報錯的訊息。
OCR 測試工具運行後馬上又會消失
![bbb](https://user-images.githubusercontent.com/65601335/127740641-07fbd394-a9b2-432e-a859-1f48d22e26b7.jpg)
![aaa](https://user-images.githubusercontent.com/65601335/127740642-47af29b6-39e3-4cdc-bc39-44429125382a.png)

**Comment by PantsuDango** [comment]
我看出来了,OCR识别失败了

**Comment by PantsuDango** [comment]
我看出来了，OCR运行失败了

**Comment by PantsuDango** [comment]
我看出来了，OCR运行失败了
-----------------------------------------
1. 先确认内存是不是太低了，4G及以下应该是不够跑离线ocr的；
2. 确认杀毒软件是不是都关了，有可能被杀毒强制关了；
3. 虚拟内存太低了，需要调高，https://jingyan.baidu.com/article/67508eb402aeb19cca1ce4a7.html
以上重试都没用，团子就爱莫能助了

**Comment by PantsuDango** [comment]
请尝试最新版本翻译器下的本地OCR，已修复此问题
