### ISSUE TITLE
本地OCR相关：会将“....”识别成“oooo”

### ISSUE THREAD

**Issue by TeoZler** [PantsuDango/Dango-Translator#38]
![image](https://user-images.githubusercontent.com/43093562/127698339-07092e0d-fbfb-4769-979b-26d355ffabd3.png)
![image](https://user-images.githubusercontent.com/43093562/127698353-b16fb6fb-c631-4e34-9e67-f333b2808095.png)
如题

**Comment by PantsuDango** [comment]
![图片](https://user-images.githubusercontent.com/61474148/127698691-77001b2b-7249-4721-af78-6642454ab46a.png)
可以通过此功能直接替换或屏蔽oooo

**Comment by TeoZler** [comment]
啊，没注意有这个功能，谢谢解答orz
