### ISSUE TITLE
東西很棒 可惜在OBS上有一個小問題

### ISSUE THREAD

**Issue by cs10108** [PantsuDango/Dango-Translator#4]
我本機windows7環境 用最新版本obs studio
打算分開2個視窗擷取同時錄下遊戲畫面和翻譯機畫面
可是obs視窗擷取翻譯機只能獲得黑色畫面
用顯示器擷取全屏當然是沒問題的
可是這種擷取限制全屏30幀 想錄60幀就沒辦法了
如果可以讓obs擷取到就好了

**Comment by PantsuDango** [comment]
您好，obs是一个录屏软件吧。
我不知道obs识别任务栏应用程序的原理是什么，没法分析出它为什么识别不出我的软件。
或许是因为，obs只能识别有在网上注册过的软件，像我这类个人开发没有注册过软件就不认识？
可能是这样，我猜的，不能分析出obs识别原则，也就没办法对症下药...
遗憾 等我知道方法，我会尝试修复它的

**Comment by cs10108** [comment]
稍微的了解下 obs在win7環境下好像是用bitblt擷取視窗
是一種windows GDI BitBlt function
win10倒是用了一種新的方法 我
理論上obs應該會是用一些比較通用的方法來擷取視窗
盡量做到所有程式都能用 所以我是覺得OBS不是故意識別已注册軟件

感覺上可能是因為翻譯文字那區域有透明度影響到擷取視窗(0~100%都黑)
設置面板沒有透明度 OBS正常能看到
希望幫到你吧

**Comment by PantsuDango** [comment]
您好。
虽然很不好意思，其实我是推荐你换一个录屏软件的23333
我个人是用oCam来录制我的屏幕的，我觉得它很棒ww
我目前没有想到有好的办法可以解决和obs的兼容性问题.....
