### ISSUE TITLE
可以提个小建议嘛>_<

### ISSUE THREAD

**Issue by DemonPaean** [PantsuDango/Dango-Translator#41]
有没有可能加个选项让翻译后面加上渠道，例如百度翻译的最后加上一个（百
这样可以比较方便的知道哪个翻译质量好一些 0.0 现在的是按照返回顺序直接显示的

还有个小问题，362是改了离线ocr识别逻辑嘛。。。静态图也一直在识别。。。361配1.2倒是还是和以前一样。。。

么么哒~

**Comment by PantsuDango** [comment]
有没有可能加个选项让翻译后面加上渠道，例如百度翻译的最后加上一个（百
这样可以比较方便的知道哪个翻译质量好一些 0.0 现在的是按照返回顺序直接显示的
回复：之前有过一段时间是给每个翻译源加上前缀，不过太影响视觉了。然后就是用颜色来区分，我是希望大家都用颜色区分，因为每个翻译源都可以自定义颜色。

还有个小问题，362是改了离线ocr识别逻辑嘛。。。静态图也一直在识别。。。361配1.2倒是还是和以前一样。。。
不会啊，整个翻译流程是这样的，判断前后2次截图的相似度 < 98% → OCR识别 → 判断前后2次识别到的文字相似度 < 90% → 调取翻译 → 打印结果。实际上是有98%和和90%两道过滤条件避免重复翻译的

**Comment by DemonPaean** [comment]
啊对，我的锅我改成看的舒服的颜色以后就直接把改色这茬给忘了QAQ

咦奇怪我明天重装下试试看，可能是我这的问题，我这个系统有毛病没法识别杂牌的蓝牙设备一直撑着没管想直接更win11 = =

谢谢回复，么~
