### ISSUE TITLE
请求加入选择框切换功能，可以在保存的多个选择框直接切换.

### ISSUE THREAD

**Issue by CatCars** [PantsuDango/Dango-Translator#48]
离线OCR的准率让人惊喜.只要不是太特殊的字体都可以正常识别.作者大大🐮🍺。
但目前使用下来碰到了一个非常影响使用的问题.导致无法正常使用。
因为文本位置不是固定的，
比如敌人对话文本在左上角.主角对话文本在屏幕正下方，游戏系统文本在中间.
所游戏中要经常调整拾取框位置（全选的话识别准确率惨不忍睹）。
每次位置变动都需要alt+tsp或者win切出来（那种锁定鼠标的游戏会导致无法框选位置，鼠标固定在中间），然后f2框选f1开启翻译。之前一直也就这么对付用了，热键切几次窗口失效了那鼠标点菜单也不是不能用。
但是之后发现，部分游戏频繁切换窗口会有概率卡死.导致无法正常游戏.这下彻底用不了了

求大佬更新个可以在多个预设位置切换拾取框的功能。🧎‍♀️求

**Comment by PantsuDango** [comment]
多选框功能已在新版本支持，可直接更新使用，详见 [B站动态](https://www.bilibili.com/opus/732804365274841136?spm_id_from=333.999.0.0)
