### ISSUE TITLE
绑定邮箱发送验证码后卡死闪退

### ISSUE THREAD

**Issue by INDEXxiaoxia** [PantsuDango/Dango-Translator#53]
绑定邮箱发送验证码后卡死闪
![AVN8UP{P{@X@THJI`{%LC9M](https://user-images.githubusercontent.com/43598840/144740655-4f7736e5-2637-4b95-b45e-79309d17bf5e.png)

**Comment by PantsuDango** [comment]
此问题新版本已修复
