### ISSUE TITLE
DeepL輸入的字句會不斷往上累加

### ISSUE THREAD

**Issue by jo4y4y94** [PantsuDango/Dango-Translator#56]
你好 
我發現使用DeepL作為翻譯源時
OCR偵測到的字句會不斷疊加上去
例如 OCR在第一楨偵測到句子A 第二楨偵測到句子B
照理說應該要在第二楨時顯示句子B的翻譯結果
但是使用deepL時會顯示A+B的翻譯結果
並且在此之後不斷往上累加 變成翻譯A+B+C....不會消除之前的句子
導致最後deepL翻譯的篇幅非常大

**Comment by PantsuDango** [comment]
您好，这个问题我已经收录了，会好好排查看看，暂时还没法给你答复，修复好了会在下次4.0.5的更新中加入，感谢反馈

**Comment by jo4y4y94** [comment]
已經看到新版本了，大佬效率真高，想請問要怎麼更新到4.0.5版本呢?

**Comment by PantsuDango** [comment]
打开翻译器如果有更新就会提示，然后自动更新的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月26日(星期天) 晚上6:40
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] DeepL輸入的字句會不斷往上累加 (Issue #56)





 
已經看到新版本了，大佬效率真高，想請問要怎麼更新到4.0.5版本呢?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PantsuDango** [comment]
此issu我先关闭啦~
