### ISSUE TITLE
建议加入ORC预处理功能

### ISSUE THREAD

**Issue by NGXAS** [PantsuDango/Dango-Translator#59]
比如**OTSU**，连通分量等二值化的预处理，应该可以显著提升识别准确度，如果已经自带了该功能则希望可以自定义二值化的处理方式，也可以在一定程度上提升识别准确度

**Comment by PantsuDango** [comment]
谢谢建议，我会在实验之后考虑是否这样优化，OCR用的是 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR)，你也可以安装试试，看看这样处理会不会效果更好
