### ISSUE TITLE
Mac版本

### ISSUE THREAD

**Issue by L1cardo** [PantsuDango/Dango-Translator#6]
请问作者能发布Mac版本吗？
我看了下pyqt做的gui，不知道Mac能不能用

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by PantsuDango** [comment]
您好，很遗憾，我没有mac电脑，没有mac环境可以给我操作来打包程序....

**Comment by L1cardo** [comment]
用vmware装个虚拟机吧，不是很难

**Comment by PantsuDango** [comment]
之前尝试过了，我的电脑内存只有8G，跑起来很卡很卡。
或许你可以试试直接用我的代码在mac上跑起来

**Comment by L1cardo** [comment]
那麻烦需要什么包请写个requirement文件吧

**Comment by PantsuDango** [comment]
已更新requirement.txt

**Comment by chadspring** [comment]
> 那麻烦需要什么包请写个requirement文件吧

在mac上实现了吗？我没折腾成功耶

**Comment by PantsuDango** [comment]
根目录就有requirements.txt呀，https://github.com/PantsuDango/Dango-Translator/blob/master/requirements.txt


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月31日(星期四) 下午2:11
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] Mac版本 (#6)





  
那麻烦需要什么包请写个requirement文件吧
  
在mac上实现了吗？我没折腾成功耶
