### ISSUE TITLE
cp950編碼問題

### ISSUE THREAD

**Issue by Chester98053** [PantsuDango/Dango-Translator#61]
運行本地ORC時發生錯誤：
File "C:\DangoTranslator\app\ocr\Python\Lib\site-packages\click\utils.py", line 298, in echo
    file.write(out)  # type: ignore
UnicodeEncodeError: 'cp950' codec can't encode character '\u56e2' in position 16: illegal multibyte sequence
WARNING:werkzeug: * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.

好像是cp950編碼有問題，**file.write(out)**改成**file.write(out,encoding='UTF-8')**又出現其他問題，請問作者有其他解決方法嗎?

**Comment by PantsuDango** [comment]
这个应该是繁中系统编码问题导致的，可以直接加我qq，我愿意远程尝试帮你解决此问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月22日(星期六) 下午4:39
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] cp950編碼問題 (Issue #61)





 
運行本地ORC時發生錯誤：
 File "C:\DangoTranslator\app\ocr\Python\Lib\site-packages\click\utils.py", line 298, in echo
 file.write(out)  # type: ignore
 UnicodeEncodeError: 'cp950' codec can't encode character '\u56e2' in position 16: illegal multibyte sequence
 WARNING:werkzeug: * Running on all addresses.
 WARNING: This is a development server. Do not use it in a production deployment.
 
好像是cp950編碼有問題，**file.write(out)改成file.write(out,encoding='UTF-8')**又出現其他問題，請問作者有其他解決方法嗎?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chester98053** [comment]
感謝作者你的回覆。
根據你指出的問題，我從控制台更改系統語言或更改為UTF-8編碼就可以執行ORC，並且可以完成翻譯。
這是一款很棒的軟體，感謝你。

**Comment by PantsuDango** [comment]
如果方便的话，可以分享你的具体操作吗，我会同步在教程里分享给其他遇到此问题的用户




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月23日(星期天) 下午4:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] cp950編碼問題 (Issue #61)





 
感謝作者你的回覆。
 根據你指出的問題，我從控制台更改系統語言或更改為UTF-8編碼就可以執行ORC，並且可以完成翻譯。
 這是一款很棒的軟體，感謝你。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chester98053** [comment]
沒問題，希望能幫到有同樣問題的用戶。
在這邊我只介紹最簡單的方法(Python初學者而已)，若有其他更好方法也歡迎提出。

以下名稱可能會因電腦系統不同而有所差異，另外以下步驟是在Window系統上執行。

1. 開啟**控制台**
2. 點選**時鐘和區域**
3. 點選**地區**
4. 上方切換至**系統管理**
5. 在**非 Unicode 程式的語言**欄位點擊**變更系統地區設定**
6. 若是**中文(繁體，台灣)**或其他**繁體語系**切換為**中文(簡體，中國)**
    6.1.在這邊可以直接勾選**Beta:使用Unicode UTF-8 提供全球言支援**就好，但CMD上的簡體會變亂碼

再次強調，以上方法只是我的淺見，如果能起到拋磚引玉之效那是最好的。

**Comment by PantsuDango** [comment]
非常感谢你分享你的方法，我会在其他用户问到此问题时分享你的方法给他们；
另外想问下，对于看习惯繁体的用户，如果系统切到简体会不会很不习惯




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月23日(星期天) 晚上7:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] cp950編碼問題 (Issue #61)





 
沒問題，希望能幫到有同樣問題的用戶。
 在這邊我只介紹最簡單的方法(Python初學者而已)，若有其他更好方法也歡迎提出。
 
以下名稱可能會因電腦系統不同而有所差異，另外以下步驟是在Window系統上執行。
  
開啟控制台
 
點選時鐘和區域
 
點選地區
 
上方切換至系統管理
 
在非 Unicode 程式的語言欄位點擊變更系統地區設定
 
若是中文(繁體，台灣)或其他繁體語系切換為中文(簡體，中國)
 6.1.在這邊可以直接勾選Beta:使用Unicode UTF-8 提供全球言支援就好，但CMD上的簡體會變亂碼
  
再次強調，以上方法只是我的淺見，如果能起到拋磚引玉之效那是最好的。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Chester98053** [comment]
對於我而言，我是看得懂大部分簡體，並無感到不適。
對於其他用戶而言，可能看不懂簡體，但給他們一個完整句子應該就能讀懂。
總而言之，簡體對於繁體用戶的使用並沒有大礙。

**Comment by PantsuDango** [comment]
最新版本的本地OCR应该不会再出现此问题，可以尝试更新，详见 [B站动态](https://www.bilibili.com/opus/765552391458127952?spm_id_from=333.999.0.0)
