### ISSUE TITLE
能不能出一个保留ocr内容的选项？

### ISSUE THREAD

**Issue by lukemin** [PantsuDango/Dango-Translator#66]
能不能出一个保留ocr内容的选项？ 现在直接翻译了ocr的内容，有时候因为断句的原因，不准确，需要修改一下。

**Comment by PantsuDango** [comment]
翻译器根目录下有个 翻译历史.txt 都在那里




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月17日(星期四) 中午11:09
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 能不能出一个保留ocr内容的选项？ (Issue #66)





 
能不能出一个保留ocr内容的选项？ 现在直接翻译了ocr的内容，有时候因为断句的原因，不准确，需要修改一下。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lukemin** [comment]
> 翻译器根目录下有个 翻译历史.txt 都在那里
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "PantsuDango/Dango-Translator" ***@***.***&gt;; 发送时间:&nbsp;2022年2月17日(星期四) 中午11:09 ***@***.***&gt;; ***@***.***&gt;; 主题:&nbsp;[PantsuDango/Dango-Translator] 能不能出一个保留ocr内容的选项？ (Issue #66) 能不能出一个保留ocr内容的选项？ 现在直接翻译了ocr的内容，有时候因为断句的原因，不准确，需要修改一下。 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

最主要的是有时候ocr出来的句子断句有问题，要是能自己手动修改之后再手动点击翻译那就完美了。

**Comment by PantsuDango** [comment]
合理，采纳，以后更新做进去

**Comment by PantsuDango** [comment]
目前最新版本已加入对ChatGPT翻译的支持，可以直接更新使用，详见 [B站动态](https://www.bilibili.com/opus/776646223265267716?spm_id_from=333.999.0.0)
