### ISSUE TITLE
中译英

### ISSUE THREAD

**Issue by wanghaisheng** [PantsuDango/Dango-Translator#67]
麻烦配置界面上添加一下中译英的选项

**Comment by PantsuDango** [comment]
目前本地ocr和在线ocr都没有针对中文训练过，目前还支持不了中文。而且一般用不到吧，需要中译英直接用网页转换不是会方便一点吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月20日(星期天) 晚上9:02
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 中译英 (Issue #67)





 
麻烦配置界面上添加一下中译英的选项
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghaisheng** [comment]
1。paddle 本身的模型识别印刷体中文无障碍的
2.对于选定框中的文字的语言 中 英日 对于咱们工具的架构丝毫没有影响吧
3.唯一我理解要改的可能是调用本地ocr的时候传参要选 中译英
要是你觉得实在没有必要的话 我回头自己研究下代码怎么改 自己modify一个也行
@PantsuDango

**Comment by PantsuDango** [comment]
如果你是指本地ocr的话，并且只是用官方自带的模型的话，那就基于这个改一下就好了&nbsp;https://github.com/PantsuDango/DangoOCR/blob/master/server/app.py




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月20日(星期天) 晚上9:18
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 中译英 (Issue #67)





 
1。paddle 本身的模型识别印刷体中文无障碍的
 2.对于选定框中的文字的语言 中 英日 对于咱们工具的架构丝毫没有影响吧
 3.唯一我理解要改的可能是调用本地ocr的时候传参要选 中译英
 要是你觉得实在没有必要的话 我回头自己研究下代码怎么改 自己modify一个也行
 @PantsuDango
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wanghaisheng** [comment]
@PantsuDango  谢谢 我的本地环境打exe包总是不成功 我试试看
