### ISSUE TITLE
本地 OCR 对引号的支持不佳

### ISSUE THREAD

**Issue by Wybxc** [PantsuDango/Dango-Translator#68]
日文中很多像这样『』的直排引号，本地 OCR 很容易错误识别为别的字符，能否优化本地 OCR 对引号识别的效果？

**Comment by PantsuDango** [comment]
本地ocr目前用的是官方的模型，团子另外有自己训练的模型搭载在在线ocr上，本地ocr不再专门去花精力训练，大佬可以自行训练和替换模型
