### ISSUE TITLE
python 3.10 用 venv 安装依赖时报错

### ISSUE THREAD

**Issue by wuyudi** [PantsuDango/Dango-Translator#69]
uname -a

Linux archlinux 5.16.12-arch1-1 #1 SMP PREEMPT Wed, 02 Mar 2022 12:22:51 +0000 x86_64 GNU/Linux

python3 -V
Python 3.10.2

```bash
./pip3 install -r ./../requirements.txt 
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/
Collecting selenium==3.141.0
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904 kB)
     |████████████████████████████████| 904 kB 1.9 MB/s 
Collecting Flask==1.1.1
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94 kB)
     |████████████████████████████████| 94 kB 1.7 MB/s 
ERROR: Could not find a version that satisfies the requirement opencv_python==4.2.0.34 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62)
ERROR: No matching distribution found for opencv_python==4.2.0.34
```

**Comment by PantsuDango** [comment]
你把依赖文件的opencv_python==4.2.0.34后面的版本号去掉 让它自动索引版本号




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月6日(星期天) 凌晨4:41
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] python 3.10 用 venv 安装依赖时报错 (Issue #69)





 ./pip3 install -r ./../requirements.txt  Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/ Collecting selenium==3.141.0   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/80/d6/4294f0b4bce4de0abf13e17190289f9d0613b0a44e5dd6a7f5ca98459853/selenium-3.141.0-py2.py3-none-any.whl (904 kB)      |████████████████████████████████| 904 kB 1.9 MB/s  Collecting Flask==1.1.1   Downloading https://pypi.tuna.tsinghua.edu.cn/packages/9b/93/628509b8d5dc749656a9641f4caf13540e2cdec85276964ff8f43bbb1d3b/Flask-1.1.1-py2.py3-none-any.whl (94 kB)      |████████████████████████████████| 94 kB 1.7 MB/s  ERROR: Could not find a version that satisfies the requirement opencv_python==4.2.0.34 (from versions: 3.4.0.14, 3.4.10.37, 3.4.11.39, 3.4.11.41, 3.4.11.43, 3.4.11.45, 3.4.13.47, 3.4.15.55, 3.4.16.57, 3.4.16.59, 3.4.17.61, 4.3.0.38, 4.4.0.40, 4.4.0.42, 4.4.0.44, 4.4.0.46, 4.5.1.48, 4.5.3.56, 4.5.4.58, 4.5.4.60, 4.5.5.62) ERROR: No matching distribution found for opencv_python==4.2.0.34
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wuyudi** [comment]
我把版本号全删了再 pip，遇到报错。

```
ModuleNotFoundError: No module named 'winreg'
```

搜了下，这个是 win 专属的。 https://stackoverflow.com/a/54237875/13040423

那这个 issue 为何能装成功 https://github.com/PantsuDango/Dango-Translator/issues/8

以及看截图是 win 的。

**Comment by PantsuDango** [comment]
建议不要删除全部版本号，只去掉opencv_python的，另外可以试试装python3.8.10

**Comment by wuyudi** [comment]
I wrote a small script, and it seems to meet my need. https://gist.github.com/wuyudi/d39be36fba365ec93115cbf7a7f417b4
