### ISSUE TITLE
Windows10系统报毒并自动删除可执行文件

### ISSUE THREAD

**Issue by Albelt** [PantsuDango/Dango-Translator#7]
![image](https://user-images.githubusercontent.com/35684393/83498386-70364d00-a4ee-11ea-9a45-9a8303958129.png)

![image](https://user-images.githubusercontent.com/35684393/83497459-18e3ad00-a4ed-11ea-8c62-d3d962b6b1d5.png)

问题如上图，从百度网盘下载解压后无法执行，然后就找不到可执行文件了。查看安全中心发现被当作木马删除了:cry:，我的系统版本号是1909。

**Comment by PantsuDango** [comment]
你应该按照文本教程最开始所说的，关掉所有杀毒和防火墙，或者将翻译器整个文件夹加入到它们的信任列表里

**Comment by Albelt** [comment]
谢谢团子:smile:，问题解决了，把 “病毒和威胁防护"设置中的实时保护关闭就行了。
