### ISSUE TITLE
使用不了本地OCR

### ISSUE THREAD

**Issue by hpps900714** [PantsuDango/Dango-Translator#71]
![image](https://user-images.githubusercontent.com/68677809/159247248-c9985fcf-a6c0-4fe5-8a65-6412c0dc2d3e.png)

**Comment by PantsuDango** [comment]
https://dango-1252620843.cos.ap-chengdu.myqcloud.com/download/ocr.zip

**Comment by PantsuDango** [comment]
你可以试试这个版本的ocr，刚出炉的

**Comment by hpps900714** [comment]
感謝 可以使用了
