### ISSUE TITLE
界面上能否加个文本输入框？

### ISSUE THREAD

**Issue by forbbs** [PantsuDango/Dango-Translator#72]
有的句子，Ocr怎么识别都不对。让我复制下来，手动修改一下原文。再输入进去翻译。

也就是某个时候，当成一个翻译器使用。

**Comment by PantsuDango** [comment]
已收到你的建议，应该也是有需求的，我是打算后面做一个可以自定义修改ocr的结果后再翻译的功能

**Comment by PantsuDango** [comment]
此功能已在新版本实现，可直接更新使用，详情可见 [B站动态](https://www.bilibili.com/opus/776646223265267716?spm_id_from=333.999.0.0)
