### ISSUE TITLE
Ver3.6.2版本貌似连不上登陆服务器

### ISSUE THREAD

**Issue by TroyLin0218** [PantsuDango/Dango-Translator#77]
如题
貌似连不上登陆服务器，截图如下：
![连接失败](https://user-images.githubusercontent.com/32014171/167284173-d1c92fe3-e26e-463a-abbe-b0df6224a69d.png)
本地直接ping截图的ip也ping不通(开不开小飞机都不太行，虽然是深圳阿里云的服务器 ==)。
此外，查询错误用Ver3.6.2.exe运行时同样报错且没有日志输出

**Comment by PantsuDango** [comment]
你这版本太老了，已经停止服务了，请使用最新版本https://translator.dango.cloud/




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月8日(星期天) 下午2:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] Ver3.6.2版本貌似连不上登陆服务器 (Issue #77)





 
如题
 貌似连不上登陆服务器，截图如下：
 
 本地直接ping截图的ip也ping不通(开不开小飞机都不太行，虽然是深圳阿里云的服务器 ==)。
 此外，查询错误用Ver3.6.2.exe运行时同样报错且没有日志输出

**Comment by PantsuDango** [comment]
此issu我先关闭啦~
