### ISSUE TITLE
win11使用最新版本闪退问题

### ISSUE THREAD

**Issue by llhhttt** [PantsuDango/Dango-Translator#78]
win11正常下载完安装程序后点击会有闪退问题

**Comment by PantsuDango** [comment]
推测是被系统防火墙或者其他杀毒软件查杀了，可以关闭所有防火墙和杀毒重新安装试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月17日(周二) 下午4:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] win11使用最新版本闪退问题 (Issue #78)




 
win11正常下载完安装程序后点击会有闪退问题

**Comment by PantsuDango** [comment]
此issu我先关闭啦~
