### ISSUE TITLE
 win11登入以后，弹出cmd一秒不到消失，后续没有任何反应

### ISSUE THREAD

**Issue by aikohime** [PantsuDango/Dango-Translator#79]
我下了火绒也没用，字体我一直都没下，后来寻思是字体的问题下了以后也显示字体缺失，依然打不开软体。
注册一切都正常，就是我没有D盘所以只能安装C盘，寻思应该问题不大，我点击要安装C盘里面他就显示不能安装到有中文字体的目录下，问题是我只是想安装到C盘的program file里根本没有中文字体。这些都不是什么大问题，只是有点bug了而已。
登入了没反应才是大问题，我看别人登入了以后就会出现cmd然后一大串的编码，第一次打开就出现了0.1秒然后就消失了，之后也没有任何反应。下载的最新的版本v4.2.5，希望能儘快解決。

**Comment by PantsuDango** [comment]
翻译器问题可以直接来QQ交流群 779594427~

会客服娘专门负责解答你的问题。
另外你的安装路径有一个空格，这个不会影响翻译器使用，但会影响本地ocr的启动

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月3日(周五) 晚上7:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator]  win11 登入以后，弹出cmd一秒不到消失，后续没有任何反应 (Issue #79)




 
我下了火绒也没用，字体我一直都没下，后来寻思是字体的问题下了以后也显示字体缺失，依然打不开软体。
 注册一切都正常，就是我没有D盘所以只能安装C盘，寻思应该问题不大，我点击要安装C盘里面他就显示不能安装到有中文字体的目录下，问题是我只是想安装到C盘的program file里根本没有中文字体。这些都不是什么大问题，只是有点bug了而已。
 登入了没反应才是大问题，我看别人登入了以后就会出现cmd然后一大串的编码，第一次打开就出现了0.1秒然后就消失了，之后也没有任何反应。下载的最新的版本v4.2.5，希望能儘快解決。

**Comment by PantsuDango** [comment]
最新版本的本地OCR应该不会再出现此问题，可以尝试更新，详见 [B站动态](https://www.bilibili.com/opus/765552391458127952?spm_id_from=333.999.0.0)
