### ISSUE TITLE
请问如何翻译竖排文字？

### ISSUE THREAD

**Issue by Hamakaze1s** [PantsuDango/Dango-Translator#80]
如题，本地ocr似乎无法正确识别竖排文字

**Comment by PantsuDango** [comment]
本地ocr不支持竖排翻译，在线和百度才支持




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月9日(星期四) 晚上8:21
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 请问如何翻译竖排文字？ (Issue #80)





 
如题，本地ocr似乎无法正确识别竖排文字

**Comment by mingtianshi** [comment]
所以你们有没有其他好的翻译器推荐呢

**Comment by PantsuDango** [comment]
> 所以你们有没有其他好的翻译器推荐呢

其他好的翻译器推荐VNR和御坂
