### ISSUE TITLE
关于百度OCR的调用问题

### ISSUE THREAD

**Issue by lianxinsuo** [PantsuDango/Dango-Translator#81]
我是5w/天的老账户，但是团子翻译器并不是调用的5w/天的标准精度，而是调用500/天的高精度，导致每天500次调用后就显示“无额度”，请问能修一下吗？

**Comment by PantsuDango** [comment]
请检查一下你是否打开了设置里的百度ocr高精度开关，如果没有打开，那调用的就是5w/天的标准精度

**Comment by lianxinsuo** [comment]
> 请检查一下你是否打开了设置里的百度ocr高精度开关，如果没有打开，那调用的就是5w/天的标准精度

收到收到，还有就是问下如何删除本地ocr的文件啊，空间不够用能删就删了~

**Comment by PantsuDango** [comment]
翻译器安装的根目录下，app/ocr，整个文件夹删掉



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月20日(周一) 下午4:55
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 关于百度OCR的调用问题 (Issue #81)




  
请检查一下你是否打开了设置里的百度ocr高精度开关，如果没有打开，那调用的就是5w/天的标准精度
  
收到收到，还有就是问下如何删除本地ocr的文件啊，空间不够用能删就删了~

**Comment by PantsuDango** [comment]
你在设置里把高精度模式的开关关了，就不会调高精度接口了，默认就是调普通的



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月10日(周五) 下午3:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 关于百度OCR的调用问题 (Issue #81)




 
我是5w/天的老账户，但是团子翻译器并不是调用的5w/天的标准精度，而是调用500/天的高精度，导致每天500次调用后就显示“无额度”，请问能修一下吗？
