### ISSUE TITLE
手动模式能否添加识别鼠标或回车键点击

### ISSUE THREAD

**Issue by deadblue0910** [PantsuDango/Dango-Translator#86]
识别一次点击后自动进行一次翻译

**Comment by PantsuDango** [comment]
应该不太好，那不是和正常用鼠标混在一起了，而且不是每个使用者都在玩gal...




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月7日(星期天) 凌晨2:22
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 手动模式能否添加识别鼠标或回车键点击 (Issue #86)





 
识别一次点击后自动进行一次翻译
