### ISSUE TITLE
使用需要注册帐号

### ISSUE THREAD

**Issue by mahengrui1** [PantsuDango/Dango-Translator#91]
注册帐号需要Email、验证码

**Comment by PantsuDango** [comment]
没理解您想表达什么



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月4日(周日) 凌晨2:31
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 使用需要注册帐号 (Issue #91)




 
注册帐号需要Email、验证码

**Comment by PantsuDango** [comment]
此issu我先关闭啦~
