### ISSUE TITLE
使用時 剪下熱鍵 （ctrl + x） 無法使用

### ISSUE THREAD

**Issue by WWW5911** [PantsuDango/Dango-Translator#92]
ctrl + x 會被替換成切換顯示/不顯示翻譯區域 的熱鍵
在設定中也找不到設定此的熱鍵

在文字工作時使用起來綁手綁腳，望能解決此問題

**Comment by zkd-11** [comment]
【自动回复】---         您好，我是赵楷迪，我已收到您的来信，我会尽快给您答复，谢谢！---         【收件成功】

**Comment by PantsuDango** [comment]
在设置 - 显示设定 - 最右下角的 隐藏范围热键 这里设置关闭即可




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月25日(星期天) 下午4:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[PantsuDango/Dango-Translator] 使用時 剪下熱鍵 （ctrl + x） 無法使用 (Issue #92)





 
ctrl + x 會被替換成切換顯示/不顯示翻譯區域 的熱鍵
 在設定中也找不到設定此的熱鍵
 
在文字工作時使用起來綁手綁腳，望能解決此問題

**Comment by WWW5911** [comment]
原來在那邊 不好意思
感謝

**Comment by PantsuDango** [comment]
没关系，解决了就好。后续有相关问题，可以直接来qq交流群794893584找客服解决&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PantsuDango/Dango-Translator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月25日(星期天) 下午4:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PantsuDango/Dango-Translator] 使用時 剪下熱鍵 （ctrl + x） 無法使用 (Issue #92)





 
原來在那邊 不好意思
 感謝
