### ISSUE TITLE
邮箱地址不合法

### ISSUE THREAD

**Issue by StarryMoe** [PantsuDango/Dango-Translator#95]
注册账号时，如果邮箱前缀包含英文字符“.”会在点击获取验证码时提示邮箱地址不合法

**Comment by PantsuDango** [comment]
源码里并不会把 . 当成不允许的字符，应该不是 . 导致您无法注册的，请您再检查一下是否有其他空字符导致



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月7日(周五) 下午5:30
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [PantsuDango/Dango-Translator] 邮箱地址不合法 (Issue #95)




 
注册账号时，如果邮箱前缀包含英文字符“.”会在点击获取验证码时提示邮箱地址不合法

**Comment by StarryMoe** [comment]
测试过邮箱格式 `splitpath@example.com` 可以正常点击获取验证码，但是多加一个“.”的 `split.path@example.com` 点击就会提示不合法，已检查确定没有空字符干扰
![团子翻译器_邮箱地址不合法](https://user-images.githubusercontent.com/36125045/194531817-aeca5d6d-f519-4e91-9646-af00cc793164.png)

**Comment by PantsuDango** [comment]
***@***.***这样的邮箱吗...那我得修改下正则的匹配规则了。
感谢反馈，我会在下次更新修复这个地方，但目前只能避免用这样的邮箱了，非常抱歉

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年10月7日(周五) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PantsuDango/Dango-Translator] 邮箱地址不合法 (Issue #95)




 
测试过邮箱格式 ***@***.*** 可以正常点击获取验证码，但是多加一个“.”的 ***@***.*** 点击就会提示不合法，已检查确定没有空字符干扰

**Comment by StarryMoe** [comment]
没关系，非常感谢修复

**Comment by PantsuDango** [comment]
此问题已修复
