### ISSUE TITLE
关于paddleOCR的打包问题

### ISSUE THREAD

**Issue by KJC1999** [PantsuDango/Dango-Translator#97]
大佬你好，我在你的简介中看到用到了paddleOCR，我想请问一下你是怎么打包的呢？
我在我的pyqt中也调用到paddleOCR，但是py2exe之后的包无法打开，网上也没找到特别好的方法。。
另外在打包的时候，需要把训练模型也打进去吗？打进去的包最后出来的包好像很大

**Comment by PantsuDango** [comment]
我是用这个打包的 [QPT](https://github.com/QPT-Family/QPT) ，你可以试试 ~

**Comment by KJC1999** [comment]
嗯，我在下面看到了QPT，在windows环境确实正常了，但是我本人主要用的环境是mac，mac太孤儿了哈哈，就py2installer和py2app能用

**Comment by PantsuDango** [comment]
此issu我先关闭啦~
