### ISSUE TITLE
关于二次开发的困惑

### ISSUE THREAD

**Issue by ccdesue** [PantsuDango/Dango-Translator#98]
这是个很棒的软件！综合看下来使用体验最佳，而且模块清晰，二次开发比较容易

最近，我正在尝试给这个软件加入自定义ocr请求模块，但在开发中遇到了一些问题

比如
1.  窗口内部逻辑函数发生错误，没有任何提示信息
2.  调试困难 只能print或者logging  修改代码只能重新启动

我对pyqt了解甚少，请问下有什么方便开发的建议吗？

**Comment by ccdesue** [comment]
目前功能完成了，但好像逻辑有些问题，还有一些体验上的bug....
我测试了一下，单纯是调用上好像有一些问题，导致了执行效率低下，与ocr速度无关

**Comment by PantsuDango** [comment]
关于调试问题，如果你是用ide pycharm来编辑的话，需要打开这个设置才可以看到错误信息，可见下图。其他问题好像没描述具体是什么，具体的话可以直接留个qq我加你沟通~
![image](https://user-images.githubusercontent.com/61474148/198868483-24130e96-7653-449c-83d9-91c1cb5be486.png)
